/**
 * zh overlay for the ai app.
 *
 * Generated by `npm run i18n:translate -- --locale zh`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/ai.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const zh: Record<string, string> = {
  "ai.action.add_knowledge": "添加知识",
  "ai.action.listen": "听取",
  "ai.field.knowledge_content": "AI 助手可使用的验证信息",
  "ai.field.knowledge_title": "标题",
  "ai.field.source_url": "来源 URL",
  "ai.field.target_language": "目标语言",
  "ai.message.greeting": "您好。请询问有关您的组织数据、库存、联系人或系统运作方式的信息。",
  "ai.message.knowledge_added": "知识条目已添加",
  "ai.message.microphone_denied": "麦克风不可用。",
  "ai.message.processing": "AI 正在处理...",
  "ai.message.prompt_saved": "AI 提示已保存",
  "ai.message.voice_message": "🎙 语音消息",
  "ai.scope.global": "默认",
  "ai.scope.tenant": "Tenant",
  "ai.view.engine_note": "Gemini · tenant 安全的平台工具",
  "ai.view.knowledge": "知识库",
  "ai.view.placeholder": "询问 AI 助手...",
  "ai.view.settings_subtitle": "管理此 tenant 助手的回答范围、指令和知识库。",
  "ai.view.settings_title": "AI 设置",
  "ai.view.subtitle": "{brand} AI 助手",
  "ai.view.system_prompt": "系统提示",
  "ai.view.tab_chat": "AI 聊天",
  "ai.view.tab_translate": "翻译",
  "ai.view.title": "AI 助手",
  "ai.view.translate_placeholder": "要翻译的文本...",
};
