/**
 * zh overlay for the integrations app.
 *
 * Generated by `npm run i18n:translate -- --locale zh`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/integrations.ts,
 * which hands it to registerDictionary; nothing in the core names it. It was
 * part of this locale's core.ts until 2026-08-27, when the connectors became an
 * app in client-gerege-nexus.
 */
export const zh: Record<string, string> = {
  "integrations.action.connect": "连接",
  "integrations.action.create": "添加集成",
  "integrations.action.disconnect": "断开连接",
  "integrations.action.register": "注册连接器",
  "integrations.field.auto_export": "自动将每份新签署的文档归档到此处",
  "integrations.field.calendar_id": "日历 ID（可选）",
  "integrations.field.connected_account": "已连接的账号",
  "integrations.field.drive_folder": "目标文件夹 ID（可选）",
  "integrations.field.drive_folder_placeholder": "留空表示 Drive 根目录",
  "integrations.field.dropbox_folder": "目标文件夹路径（可选）",
  "integrations.field.dropbox_folder_placeholder": "例如：合同/2026",
  "integrations.field.name": "集成名称",
  "integrations.field.name_placeholder": "例如：销售 Webhook",
  "integrations.field.secret": "密钥（签名）",
  "integrations.field.secret_placeholder": "可选 HMAC 密钥",
  "integrations.field.target_url": "目标端点 URL",
  "integrations.field.type": "集成类型",
  "integrations.message.auto_export_on": "自动归档已开启",
  "integrations.message.confirm_delete": "确定删除集成 {name} 吗？",
  "integrations.message.connect_after_save": "保存后，请使用“连接”授权该账号。",
  "integrations.message.connect_failed": "无法连接账号",
  "integrations.message.connected": "{name} 已连接。",
  "integrations.message.delete_failed": "无法删除集成",
  "integrations.message.disconnect_failed": "无法断开账号连接",
  "integrations.message.empty": "尚未注册任何集成。",
  "integrations.message.encryption_missing": "未设置 INTEGRATION_ENCRYPTION_KEY，因此无法存储密钥或账号连接。",
  "integrations.message.load_failed": "无法加载集成",
  "integrations.message.loading": "正在加载集成...",
  "integrations.message.meet_via_calendar": "Meet 链接由日历签发，因此该连接器需要日历访问权限。",
  "integrations.message.not_connected": "尚未连接账号",
  "integrations.message.register_failed": "无法注册集成",
  "integrations.state.unavailable": "不可用",
  "integrations.type.custom_rest": "自定义 REST 端点",
  "integrations.type.dropbox": "Dropbox",
  "integrations.type.google_drive": "Google Drive",
  "integrations.type.google_meet": "Google Meet",
  "integrations.type.government_gateway": "政府网关",
  "integrations.type.payment_gateway": "支付网关",
  "integrations.type.webhook": "Webhook 监听器",
  "integrations.view.create_title": "注册集成连接器",
  "integrations.view.subtitle": "管理政务网关、REST API 连接器与事件 Webhook",
  "integrations.view.title": "外部系统集成与 Webhook",
};
