/**
 * zh overlay for the storefront app.
 *
 * Generated by `npm run i18n:translate -- --locale zh`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/storefront.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const zh: Record<string, string> = {
  "storefront.action.browse": "浏览目录",
  "storefront.action.publish": "发布应用",
  "storefront.category.other": "其他",
  "storefront.stat.apps": "个应用",
  "storefront.stat.categories": "个分类",
  "storefront.stat.publishers": "位发布者",
  "storefront.view.catalogue_eyebrow": "目录",
  "storefront.view.catalogue_lede": "安装实例的管理员直接从自己的「应用商店」页面安装它们。每个版本都通过签名目录分发。",
  "storefront.view.catalogue_title": "已发布的应用",
  "storefront.view.eyebrow": "GEREGE APP STORE · 开放目录",
  "storefront.view.lede": "在 {brand} 上运行的应用的官方目录。每个应用都附带签名清单，因此实例可以验证自己正在安装的是什么。",
  "storefront.view.title_highlight": "一次装一个应用",
  "storefront.view.title_lead": "组织运行的一切，",
};
