import type { MetadataRoute } from "next";

import { brandFromEnv } from "@/lib/brandEnv";
import type { Brand } from "@/lib/brand";

/**
 * What the browser needs before it will offer to install this as an app.
 *
 * The native macOS, Windows, iOS and Android clients are a separate line of
 * work; this is the same platform installed straight from the browser, with no
 * download and no store. On a desktop it lands in the dock or the taskbar and
 * opens in its own window; on Android it goes to the home screen. The pages it
 * serves are exactly the pages the browser serves, so nothing here forks.
 *
 * Next generates this at /manifest.webmanifest and adds the <link> for it.
 */
// Per request, for the reason app/layout.tsx is: the name under the icon is
// the deployment's, and a manifest generated by `next build` would carry the
// name of whoever built the image. This is the file where that would show
// hardest — an installed app keeps what the manifest said.
export const dynamic = "force-dynamic";

// What a launcher installs.
//
// The icons that ship in the image unless the deployment named its own. A
// deployment can point at an address; it cannot put a file inside an image that
// was built without it, which is the whole reason this is an address and not an
// upload.
//
// `sizes: "any"` for a supplied icon, because the deployment's file is whatever
// size it is and this cannot measure it. Declaring 512x512 over a 144-pixel
// picture would be a claim the browser believes and then draws blurred; "any"
// is the truthful answer and is what an SVG entry says too.
function icons(brand: Brand): MetadataRoute.Manifest["icons"] {
  if (!brand.iconUrl) {
    return [
      { src: "/icons/app-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/app-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      // Separate artwork, not the same file relabelled. A launcher that crops
      // to a circle would otherwise cut the corners off the card and leave four
      // pale notches; this one bleeds to the edge and keeps the emblem inside
      // the safe zone.
      {
        src: "/icons/app-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ];
  }
  const supplied: NonNullable<MetadataRoute.Manifest["icons"]> = [
    { src: brand.iconUrl, sizes: "any", purpose: "any" },
  ];
  // Only when the deployment supplied artwork drawn for cropping. Relabelling
  // the ordinary icon maskable is how a logo loses its corners on Android and
  // nobody can say when.
  if (brand.maskableIconUrl) {
    supplied.push({ src: brand.maskableIconUrl, sizes: "any", purpose: "maskable" });
  }
  return supplied;
}

export default function manifest(): MetadataRoute.Manifest {
  const brand = brandFromEnv();
  return {
    // `id` is what the browser matches an installed copy against. It is pinned
    // rather than derived from start_url, so changing where the app opens does
    // not make every installed copy look like a different app.
    id: "/",
    name: brand.name,
    short_name: brand.shortName,
    description: brand.description,
    // Mongolian is the source language of this platform, so it is what the
    // launcher labels the icon in before the app itself has loaded a locale.
    lang: "mn",
    dir: "ltr",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "any",
    categories: ["business", "government", "productivity"],
    // The splash the launcher paints before the first frame. White rather than
    // the brand blue: the icon is blue, and blue on blue loses its edges.
    background_color: "#f9fafc",
    theme_color: brand.themeColor,
    icons: icons(brand),
    // The screens people open first. A shortcut is a long-press on the icon,
    // so this is a small list of destinations rather than a second menu.
    shortcuts: [
      {
        name: "Аппын дэлгүүр",
        short_name: "Аппууд",
        url: "/apps",
        icons: [{ src: "/icons/app-192.png", sizes: "192x192" }],
      },
      {
        name: "SSO клиентүүд",
        short_name: "SSO",
        url: "/sso-clients",
        icons: [{ src: "/icons/app-192.png", sizes: "192x192" }],
      },
      {
        name: "Тохиргоо",
        short_name: "Тохиргоо",
        url: "/settings/apps",
        icons: [{ src: "/icons/app-192.png", sizes: "192x192" }],
      },
    ],
  };
}
