/**
 * es overlay for the ai app.
 *
 * Generated by `npm run i18n:translate -- --locale es`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/ai.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const es: Record<string, string> = {
  "ai.action.add_knowledge": "Añadir conocimiento",
  "ai.action.listen": "Escuchar",
  "ai.field.knowledge_content": "Información verificada que el asistente puede usar",
  "ai.field.knowledge_title": "Título",
  "ai.field.source_url": "URL de origen",
  "ai.field.target_language": "Idioma de destino",
  "ai.message.greeting": "Hola. Pregúntame sobre los datos de tu organización, inventario, contactos o cómo funciona el sistema.",
  "ai.message.knowledge_added": "El conocimiento fue añadido",
  "ai.message.microphone_denied": "El micrófono no está disponible.",
  "ai.message.processing": "La IA está procesando…",
  "ai.message.prompt_saved": "La instrucción de IA fue guardada",
  "ai.message.voice_message": "🎙 Mensaje de voz",
  "ai.scope.global": "Predeterminado",
  "ai.scope.tenant": "Del tenant",
  "ai.view.engine_note": "Gemini · herramientas de plataforma seguras para el tenant",
  "ai.view.knowledge": "Base de conocimientos",
  "ai.view.placeholder": "Preguntar a Copiloto de IA...",
  "ai.view.settings_subtitle": "Gestiona el alcance de respuesta, las instrucciones y la base de conocimientos del asistente de IA de este tenant.",
  "ai.view.settings_title": "Configuración de IA",
  "ai.view.subtitle": "Asistente de IA de {brand}",
  "ai.view.system_prompt": "Instrucción del sistema",
  "ai.view.tab_chat": "Chat de IA",
  "ai.view.tab_translate": "Traducir",
  "ai.view.title": "Asistente de IA",
  "ai.view.translate_placeholder": "Texto a traducir…",
};
