/**
 * es overlay for the integrations app.
 *
 * Generated by `npm run i18n:translate -- --locale es`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/integrations.ts,
 * which hands it to registerDictionary; nothing in the core names it. It was
 * part of this locale's core.ts until 2026-08-27, when the connectors became an
 * app in client-gerege-nexus.
 */
export const es: Record<string, string> = {
  "integrations.action.connect": "Conectar",
  "integrations.action.create": "Añadir integración",
  "integrations.action.disconnect": "Desconectar",
  "integrations.action.register": "Registrar conector",
  "integrations.field.auto_export": "Archivar aquí automáticamente cada documento recién firmado",
  "integrations.field.calendar_id": "ID del calendario (opcional)",
  "integrations.field.connected_account": "Cuenta conectada",
  "integrations.field.drive_folder": "ID de la carpeta de destino (opcional)",
  "integrations.field.drive_folder_placeholder": "vacío significa la raíz de Drive",
  "integrations.field.dropbox_folder": "Ruta de la carpeta de destino (opcional)",
  "integrations.field.dropbox_folder_placeholder": "p. ej. Contratos/2026",
  "integrations.field.name": "Nombre de la integración",
  "integrations.field.name_placeholder": "ej. Webhook de ventas",
  "integrations.field.secret": "Clave secreta (firma)",
  "integrations.field.secret_placeholder": "Secreto HMAC opcional",
  "integrations.field.target_url": "URL del endpoint de destino",
  "integrations.field.type": "Tipo de integración",
  "integrations.message.auto_export_on": "Archivado automático activado",
  "integrations.message.confirm_delete": "¿Eliminar la integración {name}?",
  "integrations.message.connect_after_save": "Tras guardar, use Conectar para autorizar la cuenta.",
  "integrations.message.connect_failed": "No se pudo conectar la cuenta",
  "integrations.message.connected": "{name} está conectado.",
  "integrations.message.delete_failed": "No se pudo eliminar la integración",
  "integrations.message.disconnect_failed": "No se pudo desconectar la cuenta",
  "integrations.message.empty": "Aún no hay integraciones registradas.",
  "integrations.message.encryption_missing": "INTEGRATION_ENCRYPTION_KEY no está definido, así que no se pueden almacenar secretos ni conexiones de cuenta.",
  "integrations.message.load_failed": "No se pudieron cargar las integraciones",
  "integrations.message.loading": "Cargando integraciones...",
  "integrations.message.meet_via_calendar": "El enlace de Meet lo emite Calendar, por eso este conector solicita acceso al calendario.",
  "integrations.message.not_connected": "Sin cuenta conectada",
  "integrations.message.register_failed": "No se pudo registrar la integración",
  "integrations.state.unavailable": "no disponible",
  "integrations.type.custom_rest": "Endpoint REST personalizado",
  "integrations.type.dropbox": "Dropbox",
  "integrations.type.google_drive": "Google Drive",
  "integrations.type.google_meet": "Google Meet",
  "integrations.type.government_gateway": "Pasarela gubernamental",
  "integrations.type.payment_gateway": "Pasarela de pago",
  "integrations.type.webhook": "Receptor de Webhook",
  "integrations.view.create_title": "Registrar conector de integración",
  "integrations.view.subtitle": "Gestione pasarelas gubernamentales, conectores REST API y webhooks de eventos",
  "integrations.view.title": "Integraciones de sistemas externos y Webhooks",
};
