/**
 * es overlay for the storefront app.
 *
 * Generated by `npm run i18n:translate -- --locale es`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/storefront.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const es: Record<string, string> = {
  "storefront.action.browse": "Explorar el catálogo",
  "storefront.action.publish": "Publicar una aplicación",
  "storefront.category.other": "Otras",
  "storefront.stat.apps": "aplicaciones",
  "storefront.stat.categories": "categorías",
  "storefront.stat.publishers": "editores",
  "storefront.view.catalogue_eyebrow": "CATÁLOGO",
  "storefront.view.catalogue_lede": "El administrador de una instalación las instala desde su propia pantalla de Tienda de aplicaciones. Cada versión se distribuye a través del catálogo firmado.",
  "storefront.view.catalogue_title": "Aplicaciones publicadas",
  "storefront.view.eyebrow": "GEREGE APP STORE · CATÁLOGO ABIERTO",
  "storefront.view.lede": "El catálogo oficial de las aplicaciones que funcionan sobre {brand}. Cada aplicación llega con un manifiesto firmado, de modo que una instancia puede verificar lo que está instalando.",
  "storefront.view.title_highlight": "una aplicación a la vez",
  "storefront.view.title_lead": "Todo lo que una organización utiliza,",
};
