/**
 * ar overlay for the ai app.
 *
 * Generated by `npm run i18n:translate -- --locale ar`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/ai.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const ar: Record<string, string> = {
  "ai.action.add_knowledge": "إضافة معرفة",
  "ai.action.listen": "استماع",
  "ai.field.knowledge_content": "معلومات موثقة يمكن لمساعد الذكاء الاصطناعي استخدامها",
  "ai.field.knowledge_title": "العنوان",
  "ai.field.source_url": "عنوان URL للمصدر",
  "ai.field.target_language": "اللغة المستهدفة",
  "ai.message.greeting": "مرحباً. اسألني عن بيانات مؤسستك، المخزون، جهات الاتصال أو كيفية عمل النظام.",
  "ai.message.knowledge_added": "تمت إضافة إدخال المعرفة",
  "ai.message.microphone_denied": "الميكروفون غير متاح.",
  "ai.message.processing": "يعمل مساعد الذكاء الاصطناعي...",
  "ai.message.prompt_saved": "تم حفظ موجه الذكاء الاصطناعي",
  "ai.message.voice_message": "🎙 رسالة صوتية",
  "ai.scope.global": "افتراضي",
  "ai.scope.tenant": "خاص بالـ tenant",
  "ai.view.engine_note": "Gemini · أدوات منصة آمنة للـ tenant",
  "ai.view.knowledge": "قاعدة المعرفة",
  "ai.view.placeholder": "اسأل مساعد الذكاء الاصطناعي...",
  "ai.view.settings_subtitle": "إدارة نطاق الإجابة والتعليمات وقاعدة المعرفة التي يعمل منها مساعد هذا الـ tenant.",
  "ai.view.settings_title": "إعدادات الذكاء الاصطناعي",
  "ai.view.subtitle": "مساعد {brand} AI",
  "ai.view.system_prompt": "موجه النظام",
  "ai.view.tab_chat": "دردشة الذكاء الاصطناعي",
  "ai.view.tab_translate": "ترجمة",
  "ai.view.title": "مساعد AI",
  "ai.view.translate_placeholder": "نص للترجمة...",
};
