/**
 * ar overlay for the integrations app.
 *
 * Generated by `npm run i18n:translate -- --locale ar`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/integrations.ts,
 * which hands it to registerDictionary; nothing in the core names it. It was
 * part of this locale's core.ts until 2026-08-27, when the connectors became an
 * app in client-gerege-nexus.
 */
export const ar: Record<string, string> = {
  "integrations.action.connect": "ربط",
  "integrations.action.create": "إضافة تكامل",
  "integrations.action.disconnect": "فصل",
  "integrations.action.register": "تسجيل الموصّل",
  "integrations.field.auto_export": "احفظ كل مستند موقّع حديثًا هنا تلقائيًا",
  "integrations.field.calendar_id": "معرّف التقويم (اختياري)",
  "integrations.field.connected_account": "الحساب المتصل",
  "integrations.field.drive_folder": "معرّف مجلد الوجهة (اختياري)",
  "integrations.field.drive_folder_placeholder": "اتركه فارغًا للمجلد الجذر في Drive",
  "integrations.field.dropbox_folder": "مسار مجلد الوجهة (اختياري)",
  "integrations.field.dropbox_folder_placeholder": "مثال: العقود/2026",
  "integrations.field.name": "اسم التكامل",
  "integrations.field.name_placeholder": "مثال: Webhook المبيعات",
  "integrations.field.secret": "المفتاح السري (التوقيع)",
  "integrations.field.secret_placeholder": "المفتاح السري HMAC (اختياري)",
  "integrations.field.target_url": "عنوان URL للوجهة",
  "integrations.field.type": "نوع التكامل",
  "integrations.message.auto_export_on": "الحفظ التلقائي مفعّل",
  "integrations.message.confirm_delete": "هل تريد حذف تكامل {name}؟",
  "integrations.message.connect_after_save": "بعد الحفظ، استخدم «ربط» للموافقة على الحساب.",
  "integrations.message.connect_failed": "تعذّر ربط الحساب",
  "integrations.message.connected": "تم ربط {name}.",
  "integrations.message.delete_failed": "تعذّر حذف التكامل",
  "integrations.message.disconnect_failed": "تعذّر فصل الحساب",
  "integrations.message.empty": "لم يتم تسجيل أي تكامل بعد.",
  "integrations.message.encryption_missing": "لم يُضبط INTEGRATION_ENCRYPTION_KEY، لذا لا يمكن تخزين الأسرار أو ربط الحسابات.",
  "integrations.message.load_failed": "تعذّر تحميل التكاملات",
  "integrations.message.loading": "جارٍ تحميل التكاملات...",
  "integrations.message.meet_via_calendar": "يُصدر رابط Meet عبر التقويم، لذا يطلب هذا الموصّل صلاحية الوصول إلى التقويم.",
  "integrations.message.not_connected": "لم يُربط أي حساب بعد",
  "integrations.message.register_failed": "تعذّر تسجيل التكامل",
  "integrations.state.unavailable": "غير متاح",
  "integrations.type.custom_rest": "نقطة نهاية REST مخصصة",
  "integrations.type.dropbox": "Dropbox",
  "integrations.type.google_drive": "Google Drive",
  "integrations.type.google_meet": "Google Meet",
  "integrations.type.government_gateway": "بوابة الحكومة",
  "integrations.type.payment_gateway": "بوابة الدفع",
  "integrations.type.webhook": "مستمع Webhook",
  "integrations.view.create_title": "تسجيل موصل التكامل",
  "integrations.view.subtitle": "إدارة البوابات الحكومية وموصّلات REST API وwebhooks الأحداث",
  "integrations.view.title": "تكاملات الأنظمة الخارجية و Webhook",
};
