/**
 * ar overlay for the storefront app.
 *
 * Generated by `npm run i18n:translate -- --locale ar`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/storefront.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const ar: Record<string, string> = {
  "storefront.action.browse": "تصفّح الكتالوج",
  "storefront.action.publish": "انشر تطبيقًا",
  "storefront.category.other": "أخرى",
  "storefront.stat.apps": "تطبيق",
  "storefront.stat.categories": "فئة",
  "storefront.stat.publishers": "ناشر",
  "storefront.view.catalogue_eyebrow": "الكتالوج",
  "storefront.view.catalogue_lede": "يثبّت مسؤول التثبيت هذه التطبيقات من شاشة متجر التطبيقات الخاصة به. وتُوزَّع كل نسخة عبر الكتالوج الموقَّع.",
  "storefront.view.catalogue_title": "التطبيقات المنشورة",
  "storefront.view.eyebrow": "متجر تطبيقات GEREGE · كتالوج مفتوح",
  "storefront.view.lede": "الكتالوج الرسمي للتطبيقات التي تعمل على {brand}. يصل كل تطبيق ومعه بيان موقَّع، فيستطيع أي تثبيت التحقق مما يقوم بتثبيته.",
  "storefront.view.title_highlight": "تطبيقًا تلو الآخر",
  "storefront.view.title_lead": "كل ما تشغّله المؤسسة،",
};
