/**
 * ru overlay for the ai app.
 *
 * Generated by `npm run i18n:translate -- --locale ru`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/ai.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const ru: Record<string, string> = {
  "ai.action.add_knowledge": "Добавить знание",
  "ai.action.listen": "Слушать",
  "ai.field.knowledge_content": "Проверенная информация, которую может использовать AI",
  "ai.field.knowledge_title": "Заголовок",
  "ai.field.source_url": "URL источника",
  "ai.field.target_language": "Целевой язык",
  "ai.message.greeting": "Здравствуйте. Спросите меня о данных вашей организации, запасах, контактах или о том, как работает система.",
  "ai.message.knowledge_added": "Запись знаний добавлена",
  "ai.message.microphone_denied": "Микрофон недоступен.",
  "ai.message.processing": "AI обрабатывает…",
  "ai.message.prompt_saved": "Подсказка AI сохранена",
  "ai.message.voice_message": "🎙 Голосовое сообщение",
  "ai.scope.global": "По умолчанию",
  "ai.scope.tenant": "Для tenant",
  "ai.view.engine_note": "Gemini · инструменты платформы, ограниченные для tenant",
  "ai.view.knowledge": "База знаний",
  "ai.view.placeholder": "Спросите AI-помощника...",
  "ai.view.settings_subtitle": "Управление областью ответов, инструкциями и базой знаний AI-помощника этого tenant.",
  "ai.view.settings_title": "Настройки AI",
  "ai.view.subtitle": "AI-помощник {brand}",
  "ai.view.system_prompt": "Системная подсказка",
  "ai.view.tab_chat": "Чат с AI",
  "ai.view.tab_translate": "Перевод",
  "ai.view.title": "AI-помощник",
  "ai.view.translate_placeholder": "Текст для перевода…",
};
