/**
 * ru overlay for the integrations app.
 *
 * Generated by `npm run i18n:translate -- --locale ru`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/integrations.ts,
 * which hands it to registerDictionary; nothing in the core names it. It was
 * part of this locale's core.ts until 2026-08-27, when the connectors became an
 * app in client-gerege-nexus.
 */
export const ru: Record<string, string> = {
  "integrations.action.connect": "Подключить",
  "integrations.action.create": "Добавить интеграцию",
  "integrations.action.disconnect": "Отключить",
  "integrations.action.register": "Зарегистрировать коннектор",
  "integrations.field.auto_export": "Автоматически сохранять сюда каждый новый подписанный документ",
  "integrations.field.calendar_id": "ID календаря (необязательно)",
  "integrations.field.connected_account": "Подключённый аккаунт",
  "integrations.field.drive_folder": "ID папки назначения (необязательно)",
  "integrations.field.drive_folder_placeholder": "пусто — корень Drive",
  "integrations.field.dropbox_folder": "Путь к папке назначения (необязательно)",
  "integrations.field.dropbox_folder_placeholder": "например: Договоры/2026",
  "integrations.field.name": "Название интеграции",
  "integrations.field.name_placeholder": "напр.: Webhook продаж",
  "integrations.field.secret": "Секретный ключ (подпись)",
  "integrations.field.secret_placeholder": "Необязательный секрет HMAC",
  "integrations.field.target_url": "URL целевой конечной точки",
  "integrations.field.type": "Тип интеграции",
  "integrations.message.auto_export_on": "Автосохранение включено",
  "integrations.message.confirm_delete": "Удалить интеграцию {name}?",
  "integrations.message.connect_after_save": "После сохранения нажмите «Подключить», чтобы авторизовать аккаунт.",
  "integrations.message.connect_failed": "Не удалось подключить аккаунт",
  "integrations.message.connected": "{name} подключён.",
  "integrations.message.delete_failed": "Не удалось удалить интеграцию",
  "integrations.message.disconnect_failed": "Не удалось отключить аккаунт",
  "integrations.message.empty": "Интеграции ещё не зарегистрированы.",
  "integrations.message.encryption_missing": "INTEGRATION_ENCRYPTION_KEY не задан, поэтому секреты и подключения аккаунтов сохранить нельзя.",
  "integrations.message.load_failed": "Не удалось загрузить интеграции",
  "integrations.message.loading": "Загрузка интеграций...",
  "integrations.message.meet_via_calendar": "Ссылка Meet выдаётся через Календарь, поэтому этот коннектор запрашивает доступ к календарю.",
  "integrations.message.not_connected": "Аккаунт не подключён",
  "integrations.message.register_failed": "Не удалось зарегистрировать интеграцию",
  "integrations.state.unavailable": "недоступно",
  "integrations.type.custom_rest": "Пользовательская конечная точка REST",
  "integrations.type.dropbox": "Dropbox",
  "integrations.type.google_drive": "Google Drive",
  "integrations.type.google_meet": "Google Meet",
  "integrations.type.government_gateway": "Государственный шлюз",
  "integrations.type.payment_gateway": "Платежный шлюз",
  "integrations.type.webhook": "Приемник Webhook",
  "integrations.view.create_title": "Регистрация коннектора интеграции",
  "integrations.view.subtitle": "Управление государственными шлюзами, коннекторами REST API и webhooks событий",
  "integrations.view.title": "Интеграции с внешними системами и Webhook",
};
