/**
 * ru overlay for the storefront app.
 *
 * Generated by `npm run i18n:translate -- --locale ru`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/storefront.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const ru: Record<string, string> = {
  "storefront.action.browse": "Открыть каталог",
  "storefront.action.publish": "Опубликовать приложение",
  "storefront.category.other": "Прочее",
  "storefront.stat.apps": "приложений",
  "storefront.stat.categories": "категорий",
  "storefront.stat.publishers": "издателей",
  "storefront.view.catalogue_eyebrow": "КАТАЛОГ",
  "storefront.view.catalogue_lede": "Администратор установки ставит их прямо со своего экрана «Магазин приложений». Каждая версия распространяется через подписанный каталог.",
  "storefront.view.catalogue_title": "Опубликованные приложения",
  "storefront.view.eyebrow": "GEREGE APP STORE · ОТКРЫТЫЙ КАТАЛОГ",
  "storefront.view.lede": "Официальный каталог приложений, работающих на {brand}. Каждое приложение приходит с подписанным манифестом, поэтому установка может проверить, что именно она ставит.",
  "storefront.view.title_highlight": "по одному приложению",
  "storefront.view.title_lead": "Всё, чем пользуется организация,",
};
