import Foundation
import SwiftUI

/// App display language. Mirrors the Windows `ILocalizationService` cultures
/// (mn-MN / en-US / ru-RU / zh-CN).
enum AppLanguage: String, CaseIterable, Sendable, Identifiable {
    case mn
    case en
    case ru
    case zh
    case fr
    case es
    case ar

    var id: String { rawValue }

    /// Native display name shown in the Settings picker.
    var displayName: String {
        switch self {
        case .mn: return "Монгол"
        case .en: return "English"
        case .ru: return "Русский"
        case .zh: return "中文"
        case .fr: return "Français"
        case .es: return "Español"
        case .ar: return "العربية"
        }
    }

    /// Баруунаас зүүн бичиглэл (араб) — SwiftUI-ийн layoutDirection-д (docs/I18N.md).
    var isRTL: Bool { self == .ar }

    /// Windows culture this language maps to (the .resw folder it was generated from).
    var culture: String {
        switch self {
        case .mn: return "mn-MN"
        case .en: return "en-US"
        case .ru: return "ru-RU"
        case .zh: return "zh-CN"
        case .fr: return "fr-FR"
        case .es: return "es-ES"
        case .ar: return "ar-SA"
        }
    }

    /// `Locale` identifier for date/number formatting (DateFormatter etc.).
    var localeIdentifier: String {
        switch self {
        case .mn: return "mn_MN"
        case .en: return "en_US"
        case .ru: return "ru_RU"
        case .zh: return "zh_Hans"
        case .fr: return "fr_FR"
        case .es: return "es_ES"
        case .ar: return "ar"
        }
    }
}

/// Windows `ILocalizationService` port — holds the current language, persists the
/// selection, and resolves string keys against `L10nCatalog`. `@Published language`
/// drives live SwiftUI re-render when the user switches in Settings, so the whole
/// UI updates in place without a relaunch (matching the Windows `CultureChanged`
/// behaviour).
@MainActor
final class LocalizationService: ObservableObject {
    static let shared = LocalizationService()

    private static let defaultsKey = "app_language"

    @Published private(set) var language: AppLanguage

    init() {
        if let raw = UserDefaults.standard.string(forKey: Self.defaultsKey),
           let lang = AppLanguage(rawValue: raw) {
            language = lang
        } else {
            // App's primary language is Mongolian — default there.
            language = .mn
        }
    }

    func setLanguage(_ lang: AppLanguage) {
        guard lang != language else { return }
        language = lang
        UserDefaults.standard.set(lang.rawValue, forKey: Self.defaultsKey)
    }

    /// Resolve a localization key. Looks in the generated catalog, then the
    /// macOS-only extras, then falls back to Mongolian, then the raw key.
    func string(_ key: String) -> String {
        if let value = Self.catalog(for: language)[key] { return value }
        if let value = Self.extras(for: language)[key] { return value }
        if let fallback = L10nCatalog.mn[key] ?? Self.extraMn[key] { return fallback }
        return key
    }

    private static func catalog(for language: AppLanguage) -> [String: String] {
        switch language {
        case .mn: return L10nCatalog.mn
        case .en: return L10nCatalog.en
        case .ru: return L10nCatalog.ru
        case .zh: return L10nCatalog.zh
        case .fr: return L10nCatalog.fr
        case .es: return L10nCatalog.es
        case .ar: return L10nCatalog.ar
        }
    }

    private static func extras(for language: AppLanguage) -> [String: String] {
        switch language {
        case .mn: return extraMn
        case .en: return extraEn
        case .ru: return extraRu
        case .zh: return extraZh
        case .fr: return extraFr
        case .es: return extraEs
        case .ar: return extraAr
        }
    }

    /// Short alias for `string(_:)`.
    func t(_ key: String) -> String { string(key) }

    /// Inline four-way literal. The web-parity dashboard pages and SignView keep
    /// their copy inline (mirroring the Next.js pages' own inline strings) rather
    /// than in the generated catalog — this is the switch those call sites use.
    /// Шинэ хэлүүд (fr/es/ar) сонголтот: өгөөгүй бол АНГЛИ руу унана. Эдгээр нь дэлгэц
    /// дотор бичигдсэн урт хуулбар текстүүд — каталогид биш (docs/I18N.md).
    func pick(_ mn: String, _ en: String, _ ru: String, _ zh: String,
              fr: String? = nil, es: String? = nil, ar: String? = nil) -> String {
        switch language {
        case .mn: return mn
        case .en: return en
        case .ru: return ru
        case .zh: return zh
        case .fr: return fr ?? en
        case .es: return es ?? en
        case .ar: return ar ?? en
        }
    }

    // macOS-only strings that have no Windows resw counterpart. Hand-maintained
    // (the generated `L10nCatalog` is overwritten by scripts/gen_l10n.py).
    private static let extraEn: [String: String] = [
        "Settings_Language_Hint": "The language switches immediately.",
        "Settings_Startup_Title": "Startup",
        "Settings_Startup_LaunchAtLogin": "Open automatically at login",
        "Settings_Startup_BackgroundMode": "Menu bar mode (hide Dock icon)",
        "Settings_Startup_Hint": "In menu bar mode the app runs only in the top menu bar — close the window and it keeps running there.",
        "MenuBar_Open": "Open window",
        "MenuBar_Logout": "Log out",
        "MenuBar_Quit": "Quit PetroNet",
        "MenuBar_SignedIn": "Signed in",
        "MenuBar_SignedOut": "Not signed in",
        "Settings_Api_Title": "Server",
        "Settings_Api_Hint": "API URL (leave empty for the default server):",
        "Settings_About_Title": "About",
        "Settings_About_Build": "Build",
        "Settings_About_Publisher": "Publisher",
        "Settings_About_Platform": "Platform",
        "Settings_Close": "Close",
        "Nav_Verifier": "QR verification",
        // Web dashboard menu parity (Sidebar.tsx nav.* keys).
        "Nav_MyId": "My ID",
        "Nav_Logs": "Log history",
        "Nav_Devices": "Trusted devices",
        "Nav_Security": "Security",
        "Nav_TokenReader": "Token reader",
        "Nav_MyOrganizations": "My organizations",
        "Nav_Children": "My children",
        "Nav_Sign": "Signature",
        "Nav_Support": "Support",
        "Common_User": "User",
        "Update_LastChecked": "Checked",
        "Update_Available": "Update available",
        "Home_Hero_Title": "PetroNet — Mongolian Electronic ID",
        "Dashboard_Device_Registered": "Registered",
        "Dashboard_Wordmark": "NATIONAL ID",
        "Common_Loading": "Loading...",
        "Common_Checking": "Checking...",
        "Org_RegNumber_Hint": "Enter the organization's registry number.",
        "Org_List_Empty_Hint": "Register your organization and add digital signers.",
        "Org_Members_Empty": "No members",
        "Org_Reg_Short": "Reg",
        "Org_Sign_Waiting": "A confirmation request was sent to the e-ID Mongolia app on your phone",
        "Login_Left_Subtitle": "Digital citizen ID system",
        "Login_Left_Safe": "Safe",
        "Login_Left_Reliable": "Reliable",
        "Login_Left_Description": "Mongolia's unified sign-in system for the citizen digital ID.",
        "Login_NationalId_PushHint": "Enter your national or civil registry number. A notification will arrive in the e-ID Mongolia app on your phone.",
        "Login_Token_Connected": "Connected token",
        "Login_Result_KycLabel": "KYC level",
        "Common_Refresh": "Refresh",
        "Common_Details": "Details",
        "Common_Cancel": "Cancel",
        "Tokens_Connected_Header": "Connected tokens",
        "Tokens_Empty_Title": "No token found.",
        "Tokens_Empty_Hint": "Plug in your USB token and press \"Refresh\".",
        "Tokens_Default_Name": "FEITIAN token",
        "Tokens_Connected": "Connected",
        "Tokens_Disconnected": "Disconnected",
        "Tokens_Ready": "USB token ready",
        "Tokens_PlugIn": "Plug in a USB token",
        "Tokens_Disconnected_Notice": "The token was disconnected. Plug your USB token back in.",
        "Tokens_Info": "Information",
        "Tokens_Info_Name": "Name",
        "Tokens_Info_Fips": "FIPS mode",
        "Tokens_Info_Atr": "ATR",
        "Tokens_Yes": "Yes",
        "Tokens_No": "No",
        "Tokens_Section_Provision": "Configure token",
        "Tokens_Section_Csr": "CSR → Certificate (submit to backend)",
        "Tokens_Section_SignTest": "Signature test",
        "Tokens_Section_ChangePin": "Change PIN",
        "Tokens_Section_UnlockPin": "Unlock PIN (SO PIN required)",
        "Tokens_Section_ChangeSoPin": "Change admin (SO) PIN",
        "Tokens_ChangePin_Current": "Current PIN",
        "Tokens_ChangePin_New": "New PIN",
        "Tokens_ChangePin_Confirm": "Confirm new PIN",
        "Tokens_SoPin_Current": "Current SO PIN",
        "Tokens_SoPin_New": "New SO PIN",
        "Tokens_SoPin_Confirm": "Confirm new SO PIN",
        "Tokens_Unlock_SoPin": "Admin (SO) PIN",
        "Tokens_Unlock_New": "New user PIN",
        "Tokens_Unlock_Confirm": "Confirm new user PIN",
        "Tokens_ChangePin_Hint": "Update the PIN that unlocks the token's keys.",
        "Tokens_UnlockPin_Hint": "If the user PIN is locked by too many wrong attempts, unlock it with the admin (SO) PIN and set a new PIN.",
        "Tokens_ChangeSoPin_Hint": "Update the admin PIN used to configure the token and unlock PINs.",
        "Tokens_ChangePin_Action": "Change PIN",
        "Tokens_UnlockPin_Action": "Unlock PIN",
        "Tokens_ChangeSoPin_Action": "Change SO PIN",
        "Verifier_Subtitle": "Plug in your USB QR reader and scan the citizen's \"My QR\" in the app. After scanning, the citizen confirms with a PIN on their phone.",
        "Verifier_ScanField_Label": "Scan field",
        "Verifier_ScanField_Placeholder": "Focus here and scan the QR…",
        "Verifier_Sending": "Sending…",
        "Verifier_Running": "The citizen is confirming on their phone…",
        "Verifier_Code": "Verification code:",
        "Verifier_Verified": "Verified",
        "Verifier_Row_FullName": "Full name",
        "Verifier_Row_Surname": "Surname",
        "Verifier_Row_GivenName": "Given name",
        "Verifier_Row_CivilId": "Civil ID",
        "Verifier_Next": "Next",
        "Verifier_Rescan": "Scan again",
        "Verifier_Error_Expired": "Session expired. Please scan again.",
        "Verifier_Error_Refused": "The citizen declined.",
        "Verifier_Error_Timeout": "Timed out waiting for a response.",
        "Verifier_Error_Generic": "Error: invalid QR code or network failure.",
        "Sign_Field_NationalId": "Registry number",
        "Sign_Field_DocName": "Document name",
        "Sign_PickFile": "Choose file…",
        "Sign_HashReady": "Hash ready",
        "Sign_Action": "Sign",
        "Sign_Success": "Success",
        "Sign_Copy": "Copy",
        "Sign_KeyLabel": "Key label",
        "Tokens_Objects_Section": "Token objects",
        "Tokens_Objects_Pin": "Token PIN",
        "Tokens_Objects_Load": "Load objects",
        "Tokens_Objects_Import": "Import certificate",
        "Tokens_Objects_Delete": "Delete",
        "Tokens_Objects_Empty": "No objects on the token (or not loaded yet).",
        "Tokens_GenKey_Section": "Generate signing key",
        "Tokens_GenKey_Hint": "Create an EC P-256 keypair on the token (the signing key for CSR / enrollment).",
        "Tokens_GenKey_Action": "Generate key",
    ]
    /// Français — extraEn-тэй ижил түлхүүрүүд (docs/I18N.md).
    private static let extraFr: [String: String] = [
        "Settings_Language_Hint": "La langue change immédiatement.",
        "Settings_Startup_Title": "Démarrage",
        "Settings_Startup_LaunchAtLogin": "Ouvrir automatiquement à l'ouverture de session",
        "Settings_Startup_BackgroundMode": "Mode barre de menus (masquer l'icône du Dock)",
        "Settings_Startup_Hint": "En mode barre de menus, l'application ne s'exécute que dans la barre de menus — fermez la fenêtre et elle continue de fonctionner.",
        "MenuBar_Open": "Ouvrir la fenêtre",
        "MenuBar_Logout": "Se déconnecter",
        "MenuBar_Quit": "Quitter PetroNet",
        "MenuBar_SignedIn": "Connecté",
        "MenuBar_SignedOut": "Non connecté",
        "Settings_Api_Title": "Serveur",
        "Settings_Api_Hint": "URL de l'API (laisser vide pour le serveur par défaut) :",
        "Settings_About_Title": "À propos",
        "Settings_About_Build": "Build",
        "Settings_About_Publisher": "Éditeur",
        "Settings_About_Platform": "Plateforme",
        "Settings_Close": "Fermer",
        "Nav_Verifier": "Vérification par QR",
        // Web dashboard menu parity (Sidebar.tsx nav.* keys).
        "Nav_MyId": "Mon identité",
        "Nav_Logs": "Historique",
        "Nav_Devices": "Appareils de confiance",
        "Nav_Security": "Sécurité",
        "Nav_TokenReader": "Lecteur de jeton",
        "Nav_MyOrganizations": "Mes organisations",
        "Nav_Children": "Mes enfants",
        "Nav_Sign": "Signature",
        "Nav_Support": "Assistance",
        "Common_User": "Utilisateur",
        "Update_LastChecked": "Vérifié",
        "Update_Available": "Mise à jour disponible",
        "Home_Hero_Title": "PetroNet — identité électronique mongole",
        "Dashboard_Device_Registered": "Enregistré",
        "Dashboard_Wordmark": "IDENTITÉ NATIONALE",
        "Common_Loading": "Chargement…",
        "Common_Checking": "Vérification…",
        "Org_RegNumber_Hint": "Saisissez le numéro de registre de l'organisation.",
        "Org_List_Empty_Hint": "Enregistrez votre organisation et ajoutez des signataires électroniques.",
        "Org_Members_Empty": "Aucun membre",
        "Org_Reg_Short": "Reg.",
        "Org_Sign_Waiting": "Une demande de confirmation a été envoyée à l'application e-ID Mongolia sur votre téléphone",
        "Login_Left_Subtitle": "Système d'identité numérique du citoyen",
        "Login_Left_Safe": "Sûr",
        "Login_Left_Reliable": "Fiable",
        "Login_Left_Description": "Le système de connexion unifié de Mongolie pour l'identité numérique du citoyen.",
        "Login_NationalId_PushHint": "Saisissez votre numéro national ou civil. Une notification arrivera dans l'application e-ID Mongolia sur votre téléphone.",
        "Login_Token_Connected": "Token connecté",
        "Login_Result_KycLabel": "Niveau KYC",
        "Common_Refresh": "Actualiser",
        "Common_Details": "Détails",
        "Common_Cancel": "Annuler",
        "Tokens_Connected_Header": "Tokens connectés",
        "Tokens_Empty_Title": "Aucun token détecté.",
        "Tokens_Empty_Hint": "Branchez votre token USB et appuyez sur « Actualiser ».",
        "Tokens_Default_Name": "Token FEITIAN",
        "Tokens_Connected": "Connecté",
        "Tokens_Disconnected": "Déconnecté",
        "Tokens_Ready": "Token USB prêt",
        "Tokens_PlugIn": "Branchez un token USB",
        "Tokens_Disconnected_Notice": "Le token a été déconnecté. Rebranchez votre token USB.",
        "Tokens_Info": "Informations",
        "Tokens_Info_Name": "Nom",
        "Tokens_Info_Fips": "Mode FIPS",
        "Tokens_Info_Atr": "ATR",
        "Tokens_Yes": "Oui",
        "Tokens_No": "Non",
        "Tokens_Section_Provision": "Configurer le token",
        "Tokens_Section_Csr": "CSR → certificat (envoi au serveur)",
        "Tokens_Section_SignTest": "Test de signature",
        "Tokens_Section_ChangePin": "Modifier le PIN",
        "Tokens_Section_UnlockPin": "Déverrouiller le PIN (PIN SO requis)",
        "Tokens_Section_ChangeSoPin": "Modifier le PIN administrateur (SO)",
        "Tokens_ChangePin_Current": "PIN actuel",
        "Tokens_ChangePin_New": "Nouveau PIN",
        "Tokens_ChangePin_Confirm": "Confirmer le nouveau PIN",
        "Tokens_SoPin_Current": "PIN SO actuel",
        "Tokens_SoPin_New": "Nouveau PIN SO",
        "Tokens_SoPin_Confirm": "Confirmer le nouveau PIN SO",
        "Tokens_Unlock_SoPin": "PIN administrateur (SO)",
        "Tokens_Unlock_New": "Nouveau PIN utilisateur",
        "Tokens_Unlock_Confirm": "Confirmer le nouveau PIN utilisateur",
        "Tokens_ChangePin_Hint": "Modifiez le PIN qui déverrouille les clés du token.",
        "Tokens_UnlockPin_Hint": "Si le PIN utilisateur est verrouillé après trop d'essais erronés, déverrouillez-le avec le PIN administrateur (SO) et définissez un nouveau PIN.",
        "Tokens_ChangeSoPin_Hint": "Modifiez le PIN administrateur utilisé pour configurer le token et déverrouiller les PIN.",
        "Tokens_ChangePin_Action": "Modifier le PIN",
        "Tokens_UnlockPin_Action": "Déverrouiller le PIN",
        "Tokens_ChangeSoPin_Action": "Modifier le PIN SO",
        "Verifier_Subtitle": "Branchez votre lecteur QR USB et scannez le « Mon QR » du citoyen dans l'application. Après le scan, le citoyen confirme avec un PIN sur son téléphone.",
        "Verifier_ScanField_Label": "Champ de scan",
        "Verifier_ScanField_Placeholder": "Cliquez ici et scannez le QR…",
        "Verifier_Sending": "Envoi…",
        "Verifier_Running": "Le citoyen confirme sur son téléphone…",
        "Verifier_Code": "Code de vérification :",
        "Verifier_Verified": "Vérifié",
        "Verifier_Row_FullName": "Nom complet",
        "Verifier_Row_Surname": "Nom",
        "Verifier_Row_GivenName": "Prénom",
        "Verifier_Row_CivilId": "Identifiant civil",
        "Verifier_Next": "Suivant",
        "Verifier_Rescan": "Scanner à nouveau",
        "Verifier_Error_Expired": "Session expirée. Veuillez scanner à nouveau.",
        "Verifier_Error_Refused": "Le citoyen a refusé.",
        "Verifier_Error_Timeout": "Délai d'attente dépassé.",
        "Verifier_Error_Generic": "Erreur : code QR invalide ou défaillance réseau.",
        "Sign_Field_NationalId": "Numéro de registre",
        "Sign_Field_DocName": "Nom du document",
        "Sign_PickFile": "Choisir un fichier…",
        "Sign_HashReady": "Empreinte prête",
        "Sign_Action": "Signer",
        "Sign_Success": "Réussi",
        "Sign_Copy": "Copier",
        "Sign_KeyLabel": "Libellé de la clé",
        "Tokens_Objects_Section": "Objets du token",
        "Tokens_Objects_Pin": "PIN du token",
        "Tokens_Objects_Load": "Charger les objets",
        "Tokens_Objects_Import": "Importer un certificat",
        "Tokens_Objects_Delete": "Supprimer",
        "Tokens_Objects_Empty": "Aucun objet sur le token (ou pas encore chargé).",
        "Tokens_GenKey_Section": "Générer une clé de signature",
        "Tokens_GenKey_Hint": "Créez une paire de clés EC P-256 sur le token (la clé de signature pour la CSR / l'enrôlement).",
        "Tokens_GenKey_Action": "Générer la clé",
    ]
    /// Español — extraEn-тэй ижил түлхүүрүүд (docs/I18N.md).
    private static let extraEs: [String: String] = [
        "Settings_Language_Hint": "El idioma cambia de inmediato.",
        "Settings_Startup_Title": "Inicio",
        "Settings_Startup_LaunchAtLogin": "Abrir automáticamente al iniciar sesión",
        "Settings_Startup_BackgroundMode": "Modo barra de menús (ocultar el icono del Dock)",
        "Settings_Startup_Hint": "En el modo barra de menús, la aplicación se ejecuta solo en la barra superior: cierre la ventana y seguirá funcionando ahí.",
        "MenuBar_Open": "Abrir la ventana",
        "MenuBar_Logout": "Cerrar sesión",
        "MenuBar_Quit": "Salir de PetroNet",
        "MenuBar_SignedIn": "Sesión iniciada",
        "MenuBar_SignedOut": "Sesión no iniciada",
        "Settings_Api_Title": "Servidor",
        "Settings_Api_Hint": "URL de la API (déjelo vacío para el servidor predeterminado):",
        "Settings_About_Title": "Acerca de",
        "Settings_About_Build": "Compilación",
        "Settings_About_Publisher": "Editor",
        "Settings_About_Platform": "Plataforma",
        "Settings_Close": "Cerrar",
        "Nav_Verifier": "Verificación por QR",
        // Web dashboard menu parity (Sidebar.tsx nav.* keys).
        "Nav_MyId": "Mi identidad",
        "Nav_Logs": "Historial",
        "Nav_Devices": "Dispositivos de confianza",
        "Nav_Security": "Seguridad",
        "Nav_TokenReader": "Lector de token",
        "Nav_MyOrganizations": "Mis organizaciones",
        "Nav_Children": "Mis hijos",
        "Nav_Sign": "Firma",
        "Nav_Support": "Soporte",
        "Common_User": "Usuario",
        "Update_LastChecked": "Comprobado",
        "Update_Available": "Actualización disponible",
        "Home_Hero_Title": "PetroNet — identidad electrónica de Mongolia",
        "Dashboard_Device_Registered": "Registrado",
        "Dashboard_Wordmark": "IDENTIDAD NACIONAL",
        "Common_Loading": "Cargando…",
        "Common_Checking": "Comprobando…",
        "Org_RegNumber_Hint": "Introduzca el número de registro de la organización.",
        "Org_List_Empty_Hint": "Registre su organización y añada firmantes electrónicos.",
        "Org_Members_Empty": "Sin miembros",
        "Org_Reg_Short": "Reg.",
        "Org_Sign_Waiting": "Se envió una solicitud de confirmación a la aplicación e-ID Mongolia de su teléfono",
        "Login_Left_Subtitle": "Sistema de identidad digital del ciudadano",
        "Login_Left_Safe": "Seguro",
        "Login_Left_Reliable": "Fiable",
        "Login_Left_Description": "El sistema unificado de inicio de sesión de Mongolia para la identidad digital del ciudadano.",
        "Login_NationalId_PushHint": "Introduzca su número nacional o civil. Llegará una notificación a la aplicación e-ID Mongolia de su teléfono.",
        "Login_Token_Connected": "Token conectado",
        "Login_Result_KycLabel": "Nivel KYC",
        "Common_Refresh": "Actualizar",
        "Common_Details": "Detalles",
        "Common_Cancel": "Cancelar",
        "Tokens_Connected_Header": "Tokens conectados",
        "Tokens_Empty_Title": "No se encontró ningún token.",
        "Tokens_Empty_Hint": "Conecte su token USB y pulse «Actualizar».",
        "Tokens_Default_Name": "Token FEITIAN",
        "Tokens_Connected": "Conectado",
        "Tokens_Disconnected": "Desconectado",
        "Tokens_Ready": "Token USB listo",
        "Tokens_PlugIn": "Conecte un token USB",
        "Tokens_Disconnected_Notice": "El token se desconectó. Vuelva a conectar su token USB.",
        "Tokens_Info": "Información",
        "Tokens_Info_Name": "Nombre",
        "Tokens_Info_Fips": "Modo FIPS",
        "Tokens_Info_Atr": "ATR",
        "Tokens_Yes": "Sí",
        "Tokens_No": "No",
        "Tokens_Section_Provision": "Configurar el token",
        "Tokens_Section_Csr": "CSR → certificado (enviar al servidor)",
        "Tokens_Section_SignTest": "Prueba de firma",
        "Tokens_Section_ChangePin": "Cambiar el PIN",
        "Tokens_Section_UnlockPin": "Desbloquear el PIN (se requiere PIN de SO)",
        "Tokens_Section_ChangeSoPin": "Cambiar el PIN de administrador (SO)",
        "Tokens_ChangePin_Current": "PIN actual",
        "Tokens_ChangePin_New": "PIN nuevo",
        "Tokens_ChangePin_Confirm": "Confirmar el PIN nuevo",
        "Tokens_SoPin_Current": "PIN de SO actual",
        "Tokens_SoPin_New": "PIN de SO nuevo",
        "Tokens_SoPin_Confirm": "Confirmar el PIN de SO nuevo",
        "Tokens_Unlock_SoPin": "PIN de administrador (SO)",
        "Tokens_Unlock_New": "PIN de usuario nuevo",
        "Tokens_Unlock_Confirm": "Confirmar el PIN de usuario nuevo",
        "Tokens_ChangePin_Hint": "Cambie el PIN que desbloquea las claves del token.",
        "Tokens_UnlockPin_Hint": "Si el PIN de usuario se bloquea por demasiados intentos incorrectos, desbloquéelo con el PIN de administrador (SO) y establezca uno nuevo.",
        "Tokens_ChangeSoPin_Hint": "Cambie el PIN de administrador usado para configurar el token y desbloquear los PIN.",
        "Tokens_ChangePin_Action": "Cambiar el PIN",
        "Tokens_UnlockPin_Action": "Desbloquear el PIN",
        "Tokens_ChangeSoPin_Action": "Cambiar el PIN de SO",
        "Verifier_Subtitle": "Conecte su lector QR USB y escanee el «Mi QR» del ciudadano en la aplicación. Tras el escaneo, el ciudadano confirma con un PIN en su teléfono.",
        "Verifier_ScanField_Label": "Campo de escaneo",
        "Verifier_ScanField_Placeholder": "Haga clic aquí y escanee el QR…",
        "Verifier_Sending": "Enviando…",
        "Verifier_Running": "El ciudadano está confirmando en su teléfono…",
        "Verifier_Code": "Código de verificación:",
        "Verifier_Verified": "Verificado",
        "Verifier_Row_FullName": "Nombre completo",
        "Verifier_Row_Surname": "Apellido",
        "Verifier_Row_GivenName": "Nombre",
        "Verifier_Row_CivilId": "Identificador civil",
        "Verifier_Next": "Siguiente",
        "Verifier_Rescan": "Escanear de nuevo",
        "Verifier_Error_Expired": "La sesión ha caducado. Escanee de nuevo.",
        "Verifier_Error_Refused": "El ciudadano lo rechazó.",
        "Verifier_Error_Timeout": "Se agotó el tiempo de espera.",
        "Verifier_Error_Generic": "Error: código QR no válido o fallo de red.",
        "Sign_Field_NationalId": "Número de registro",
        "Sign_Field_DocName": "Nombre del documento",
        "Sign_PickFile": "Elegir archivo…",
        "Sign_HashReady": "Hash listo",
        "Sign_Action": "Firmar",
        "Sign_Success": "Correcto",
        "Sign_Copy": "Copiar",
        "Sign_KeyLabel": "Etiqueta de la clave",
        "Tokens_Objects_Section": "Objetos del token",
        "Tokens_Objects_Pin": "PIN del token",
        "Tokens_Objects_Load": "Cargar objetos",
        "Tokens_Objects_Import": "Importar certificado",
        "Tokens_Objects_Delete": "Eliminar",
        "Tokens_Objects_Empty": "No hay objetos en el token (o aún no se han cargado).",
        "Tokens_GenKey_Section": "Generar clave de firma",
        "Tokens_GenKey_Hint": "Cree un par de claves EC P-256 en el token (la clave de firma para la CSR / emisión).",
        "Tokens_GenKey_Action": "Generar clave",
    ]
    /// العربية (RTL) — extraEn-тэй ижил түлхүүрүүд (docs/I18N.md).
    private static let extraAr: [String: String] = [
        "Settings_Language_Hint": "تتغيّر اللغة فوراً.",
        "Settings_Startup_Title": "بدء التشغيل",
        "Settings_Startup_LaunchAtLogin": "الفتح تلقائياً عند تسجيل الدخول",
        "Settings_Startup_BackgroundMode": "وضع شريط القوائم (إخفاء أيقونة Dock)",
        "Settings_Startup_Hint": "في وضع شريط القوائم يعمل التطبيق في الشريط العلوي فقط — أغلق النافذة وسيظل يعمل هناك.",
        "MenuBar_Open": "فتح النافذة",
        "MenuBar_Logout": "تسجيل الخروج",
        "MenuBar_Quit": "إنهاء PetroNet",
        "MenuBar_SignedIn": "تم تسجيل الدخول",
        "MenuBar_SignedOut": "لم يتم تسجيل الدخول",
        "Settings_Api_Title": "الخادم",
        "Settings_Api_Hint": "عنوان API (اتركه فارغاً للخادم الافتراضي):",
        "Settings_About_Title": "حول التطبيق",
        "Settings_About_Build": "الإصدار البنائي",
        "Settings_About_Publisher": "الناشر",
        "Settings_About_Platform": "المنصة",
        "Settings_Close": "إغلاق",
        "Nav_Verifier": "التحقق برمز QR",
        // Web dashboard menu parity (Sidebar.tsx nav.* keys).
        "Nav_MyId": "هويتي",
        "Nav_Logs": "سجل النشاط",
        "Nav_Devices": "الأجهزة الموثوقة",
        "Nav_Security": "الأمان",
        "Nav_TokenReader": "قارئ الرمز",
        "Nav_MyOrganizations": "منظماتي",
        "Nav_Children": "أطفالي",
        "Nav_Sign": "التوقيع",
        "Nav_Support": "الدعم",
        "Common_User": "المستخدم",
        "Update_LastChecked": "تم الفحص",
        "Update_Available": "يتوفر تحديث",
        "Home_Hero_Title": "PetroNet — الهوية الإلكترونية المنغولية",
        "Dashboard_Device_Registered": "مسجَّل",
        "Dashboard_Wordmark": "الهوية الوطنية",
        "Common_Loading": "جارٍ التحميل…",
        "Common_Checking": "جارٍ الفحص…",
        "Org_RegNumber_Hint": "أدخل رقم سجل المؤسسة.",
        "Org_List_Empty_Hint": "سجّل مؤسستك وأضف موقّعين إلكترونيين.",
        "Org_Members_Empty": "لا يوجد أعضاء",
        "Org_Reg_Short": "سجل",
        "Org_Sign_Waiting": "تم إرسال طلب تأكيد إلى تطبيق e-ID Mongolia على هاتفك",
        "Login_Left_Subtitle": "نظام الهوية الرقمية للمواطن",
        "Login_Left_Safe": "آمن",
        "Login_Left_Reliable": "موثوق",
        "Login_Left_Description": "نظام تسجيل الدخول الموحّد في منغوليا للهوية الرقمية للمواطن.",
        "Login_NationalId_PushHint": "أدخل رقمك الوطني أو المدني. سيصل إشعار إلى تطبيق e-ID Mongolia على هاتفك.",
        "Login_Token_Connected": "المفتاح المتصل",
        "Login_Result_KycLabel": "مستوى KYC",
        "Common_Refresh": "تحديث",
        "Common_Details": "التفاصيل",
        "Common_Cancel": "إلغاء",
        "Tokens_Connected_Header": "المفاتيح المتصلة",
        "Tokens_Empty_Title": "لم يُعثر على مفتاح.",
        "Tokens_Empty_Hint": "وصّل مفتاح USB واضغط «تحديث».",
        "Tokens_Default_Name": "مفتاح FEITIAN",
        "Tokens_Connected": "متصل",
        "Tokens_Disconnected": "غير متصل",
        "Tokens_Ready": "مفتاح USB جاهز",
        "Tokens_PlugIn": "وصّل مفتاح USB",
        "Tokens_Disconnected_Notice": "تم فصل المفتاح. أعد توصيل مفتاح USB.",
        "Tokens_Info": "المعلومات",
        "Tokens_Info_Name": "الاسم",
        "Tokens_Info_Fips": "وضع FIPS",
        "Tokens_Info_Atr": "ATR",
        "Tokens_Yes": "نعم",
        "Tokens_No": "لا",
        "Tokens_Section_Provision": "إعداد المفتاح",
        "Tokens_Section_Csr": "CSR ← الشهادة (الإرسال إلى الخادم)",
        "Tokens_Section_SignTest": "اختبار التوقيع",
        "Tokens_Section_ChangePin": "تغيير رمز PIN",
        "Tokens_Section_UnlockPin": "فتح قفل PIN (يلزم رمز SO)",
        "Tokens_Section_ChangeSoPin": "تغيير رمز المسؤول (SO)",
        "Tokens_ChangePin_Current": "رمز PIN الحالي",
        "Tokens_ChangePin_New": "رمز PIN الجديد",
        "Tokens_ChangePin_Confirm": "تأكيد رمز PIN الجديد",
        "Tokens_SoPin_Current": "رمز SO الحالي",
        "Tokens_SoPin_New": "رمز SO الجديد",
        "Tokens_SoPin_Confirm": "تأكيد رمز SO الجديد",
        "Tokens_Unlock_SoPin": "رمز المسؤول (SO)",
        "Tokens_Unlock_New": "رمز المستخدم الجديد",
        "Tokens_Unlock_Confirm": "تأكيد رمز المستخدم الجديد",
        "Tokens_ChangePin_Hint": "غيّر رمز PIN الذي يفتح مفاتيح الرمز.",
        "Tokens_UnlockPin_Hint": "إذا قُفل رمز المستخدم بسبب محاولات خاطئة كثيرة، افتحه برمز المسؤول (SO) واضبط رمزاً جديداً.",
        "Tokens_ChangeSoPin_Hint": "غيّر رمز المسؤول المستخدم لإعداد المفتاح وفتح الأرقام السرية.",
        "Tokens_ChangePin_Action": "تغيير رمز PIN",
        "Tokens_UnlockPin_Action": "فتح قفل PIN",
        "Tokens_ChangeSoPin_Action": "تغيير رمز SO",
        "Verifier_Subtitle": "وصّل قارئ QR عبر USB وامسح «رمز QR الخاص بي» للمواطن في التطبيق. بعد المسح يؤكد المواطن برمز PIN على هاتفه.",
        "Verifier_ScanField_Label": "حقل المسح",
        "Verifier_ScanField_Placeholder": "ركّز هنا وامسح رمز QR…",
        "Verifier_Sending": "جارٍ الإرسال…",
        "Verifier_Running": "المواطن يؤكد على هاتفه…",
        "Verifier_Code": "رمز التحقق:",
        "Verifier_Verified": "تم التحقق",
        "Verifier_Row_FullName": "الاسم الكامل",
        "Verifier_Row_Surname": "اسم العائلة",
        "Verifier_Row_GivenName": "الاسم الشخصي",
        "Verifier_Row_CivilId": "الرقم المدني",
        "Verifier_Next": "التالي",
        "Verifier_Rescan": "إعادة المسح",
        "Verifier_Error_Expired": "انتهت الجلسة. يرجى إعادة المسح.",
        "Verifier_Error_Refused": "رفض المواطن الطلب.",
        "Verifier_Error_Timeout": "انتهت مهلة انتظار الرد.",
        "Verifier_Error_Generic": "خطأ: رمز QR غير صالح أو عطل في الشبكة.",
        "Sign_Field_NationalId": "رقم السجل",
        "Sign_Field_DocName": "اسم المستند",
        "Sign_PickFile": "اختيار ملف…",
        "Sign_HashReady": "البصمة جاهزة",
        "Sign_Action": "توقيع",
        "Sign_Success": "تم بنجاح",
        "Sign_Copy": "نسخ",
        "Sign_KeyLabel": "تسمية المفتاح",
        "Tokens_Objects_Section": "عناصر المفتاح",
        "Tokens_Objects_Pin": "رمز PIN للمفتاح",
        "Tokens_Objects_Load": "تحميل العناصر",
        "Tokens_Objects_Import": "استيراد شهادة",
        "Tokens_Objects_Delete": "حذف",
        "Tokens_Objects_Empty": "لا توجد عناصر على المفتاح (أو لم تُحمَّل بعد).",
        "Tokens_GenKey_Section": "توليد مفتاح توقيع",
        "Tokens_GenKey_Hint": "أنشئ زوج مفاتيح EC P-256 على المفتاح (مفتاح التوقيع لـ CSR / التسجيل).",
        "Tokens_GenKey_Action": "توليد المفتاح",
    ]
    private static let extraMn: [String: String] = [
        "Settings_Language_Hint": "Хэл шилжүүлснээр UI шууд солигдоно.",
        "Settings_Startup_Title": "Эхлүүлэлт",
        "Settings_Startup_LaunchAtLogin": "Нэвтрэхэд автоматаар нээх",
        "Settings_Startup_BackgroundMode": "Менюбар горим (Dock-д харагдахгүй)",
        "Settings_Startup_Hint": "Менюбар горимд апп зөвхөн дэлгэцийн дээд менюбарт ажиллана — цонхыг хаасан ч тэндээ ажилласаар байна.",
        "MenuBar_Open": "Цонх нээх",
        "MenuBar_Logout": "Гарах",
        "MenuBar_Quit": "PetroNet-аас гарах",
        "MenuBar_SignedIn": "Нэвтэрсэн",
        "MenuBar_SignedOut": "Нэвтрээгүй",
        "Settings_Api_Title": "Сервер",
        "Settings_Api_Hint": "API URL (хоосон бол үндсэн сервер):",
        "Settings_About_Title": "Тухай",
        "Settings_About_Build": "Build",
        "Settings_About_Publisher": "Гаргагч",
        "Settings_About_Platform": "Платформ",
        "Settings_Close": "Хаах",
        "Nav_Verifier": "QR баталгаажуулалт",
        // Web dashboard menu parity (Sidebar.tsx nav.* keys).
        "Nav_MyId": "Миний ID",
        "Nav_Logs": "Лог түүх",
        "Nav_Devices": "Итгэмжит төхөөрөмж",
        "Nav_Security": "Аюулгүй байдал",
        "Nav_TokenReader": "Токен уншигч",
        "Nav_MyOrganizations": "Миний байгууллага",
        "Nav_Children": "Миний хүүхдүүд",
        "Nav_Sign": "Гарын үсэг",
        "Nav_Support": "Тусламж",
        "Common_User": "Хэрэглэгч",
        "Update_LastChecked": "Шалгасан",
        "Update_Available": "Шинэчлэлт бий",
        "Home_Hero_Title": "PetroNet — Монголын цахим иргэний үнэмлэх",
        "Dashboard_Device_Registered": "Бүртгэсэн",
        "Dashboard_Wordmark": "NATIONAL ID",
        "Common_Loading": "Уншиж байна...",
        "Common_Checking": "Шалгаж байна...",
        "Org_RegNumber_Hint": "ААН-ийн регистрийн дугаар оруулна уу.",
        "Org_List_Empty_Hint": "Байгууллагаа бүртгүүлж, тоон гарын үсэг зурагч нэмнэ.",
        "Org_Members_Empty": "Гишүүд байхгүй",
        "Org_Reg_Short": "Регистр",
        "Org_Sign_Waiting": "Утсан дээрх e-ID Mongolia апп-д баталгаажуулах хүсэлт илгээгдлээ",
        "Login_Left_Subtitle": "Цахим иргэний үнэмлэх систем",
        "Login_Left_Safe": "Аюулгүй",
        "Login_Left_Reliable": "Найдвартай",
        "Login_Left_Description": "Монгол улсын иргэний цахим үнэмлэхийн нэгдсэн нэвтрэлтийн систем.",
        "Login_NationalId_PushHint": "РД эсвэл иргэний бүртгэлийн дугаараа оруулна уу. Утсан дээрх eID Mongolia апп-д мэдэгдэл ирнэ.",
        "Login_Token_Connected": "Холбогдсон токен",
        "Login_Result_KycLabel": "KYC түвшин",
        "Common_Refresh": "Шинэчлэх",
        "Common_Details": "Дэлгэрэнгүй",
        "Common_Cancel": "Цуцлах",
        "Tokens_Connected_Header": "Холбогдсон токенууд",
        "Tokens_Empty_Title": "Токен олдсонгүй.",
        "Tokens_Empty_Hint": "USB токенээ залгаад «Шинэчлэх» товчийг дарна уу.",
        "Tokens_Default_Name": "FEITIAN токен",
        "Tokens_Connected": "Холбогдсон",
        "Tokens_Disconnected": "Холбогдоогүй",
        "Tokens_Ready": "USB токен бэлэн",
        "Tokens_PlugIn": "USB токен залгана уу",
        "Tokens_Disconnected_Notice": "Токен салгагдсан байна. USB токенээ дахин залгана уу.",
        "Tokens_Info": "Мэдээлэл",
        "Tokens_Info_Name": "Нэр",
        "Tokens_Info_Fips": "FIPS горим",
        "Tokens_Info_Atr": "ATR",
        "Tokens_Yes": "Тийм",
        "Tokens_No": "Үгүй",
        "Tokens_Section_Provision": "Токен тохируулах",
        "Tokens_Section_Csr": "CSR → Сертификат (backend-д илгээх)",
        "Tokens_Section_SignTest": "Гарын үсэг туршилт",
        "Tokens_Section_ChangePin": "PIN солих",
        "Tokens_Section_UnlockPin": "PIN тайлах (SO PIN шаардлагатай)",
        "Tokens_Section_ChangeSoPin": "Админ (SO) PIN солих",
        "Tokens_ChangePin_Current": "Одоогийн PIN",
        "Tokens_ChangePin_New": "Шинэ PIN",
        "Tokens_ChangePin_Confirm": "Шинэ PIN давтах",
        "Tokens_SoPin_Current": "Одоогийн SO PIN",
        "Tokens_SoPin_New": "Шинэ SO PIN",
        "Tokens_SoPin_Confirm": "Шинэ SO PIN давтах",
        "Tokens_Unlock_SoPin": "Админ (SO) PIN",
        "Tokens_Unlock_New": "Шинэ User PIN",
        "Tokens_Unlock_Confirm": "Шинэ User PIN давтах",
        "Tokens_ChangePin_Hint": "Токены түлхүүрийг нээх PIN кодыг шинэчилнэ.",
        "Tokens_UnlockPin_Hint": "User PIN буруу олон удаа оруулсны улмаас түгжигдсэн бол админ (SO) PIN-ээр тайлж, шинэ PIN тогтооно.",
        "Tokens_ChangeSoPin_Hint": "Токеныг тохируулах, PIN тайлахад ашигладаг админ PIN кодыг шинэчилнэ.",
        "Tokens_ChangePin_Action": "PIN солих",
        "Tokens_UnlockPin_Action": "PIN тайлах",
        "Tokens_ChangeSoPin_Action": "SO PIN солих",
        "Verifier_Subtitle": "USB QR уншигчаа залгаад иргэний апп дахь «Миний QR»-ийг уншуулна уу. Уншсаны дараа иргэн утсан дээрээ PIN-ээр баталгаажуулна.",
        "Verifier_ScanField_Label": "Уншуулах талбар",
        "Verifier_ScanField_Placeholder": "Энд фокус тавиад QR уншуулна уу…",
        "Verifier_Sending": "Илгээж байна…",
        "Verifier_Running": "Иргэн утсан дээрээ баталгаажуулж байна…",
        "Verifier_Code": "Баталгаажуулах код:",
        "Verifier_Verified": "Баталгаажлаа",
        "Verifier_Row_FullName": "Бүтэн нэр",
        "Verifier_Row_Surname": "Овог",
        "Verifier_Row_GivenName": "Нэр",
        "Verifier_Row_CivilId": "Иргэний дугаар",
        "Verifier_Next": "Дараагийнх",
        "Verifier_Rescan": "Дахин уншуулах",
        "Verifier_Error_Expired": "Хугацаа дууссан. Дахин уншуулна уу.",
        "Verifier_Error_Refused": "Иргэн татгалзсан байна.",
        "Verifier_Error_Timeout": "Хариу хүлээх хугацаа дууслаа.",
        "Verifier_Error_Generic": "Алдаа: QR код хүчингүй эсвэл сүлжээний алдаа.",
        "Sign_Field_NationalId": "Регистрийн дугаар",
        "Sign_Field_DocName": "Баримтын нэр",
        "Sign_PickFile": "Файл сонгох…",
        "Sign_HashReady": "Hash бэлэн",
        "Sign_Action": "Гарын үсэг зурах",
        "Sign_Success": "Амжилттай",
        "Sign_Copy": "Хуулах",
        "Sign_KeyLabel": "Key label",
        "Tokens_Objects_Section": "Токены доторх объектууд",
        "Tokens_Objects_Pin": "Токен PIN",
        "Tokens_Objects_Load": "Объект ачаалах",
        "Tokens_Objects_Import": "Сертификат импортлох",
        "Tokens_Objects_Delete": "Устгах",
        "Tokens_Objects_Empty": "Токен дээр объект алга (эсвэл хараахан ачаалаагүй).",
        "Tokens_GenKey_Section": "Гарын үсгийн түлхүүр үүсгэх",
        "Tokens_GenKey_Hint": "Токен дээр EC P-256 түлхүүр хос үүсгэнэ (CSR / enrollment-д ашиглах гарын үсгийн түлхүүр).",
        "Tokens_GenKey_Action": "Түлхүүр үүсгэх",
    ]
    private static let extraRu: [String: String] = [
        "Settings_Language_Hint": "Язык переключается сразу.",
        "Settings_Startup_Title": "Запуск",
        "Settings_Startup_LaunchAtLogin": "Открывать автоматически при входе в систему",
        "Settings_Startup_BackgroundMode": "Режим строки меню (скрыть значок в Dock)",
        "Settings_Startup_Hint": "В режиме строки меню приложение работает только в верхней строке меню — закройте окно, и оно продолжит работать там.",
        "MenuBar_Open": "Открыть окно",
        "MenuBar_Logout": "Выйти",
        "MenuBar_Quit": "Завершить PetroNet",
        "MenuBar_SignedIn": "Выполнен вход",
        "MenuBar_SignedOut": "Вход не выполнен",
        "Settings_Api_Title": "Сервер",
        "Settings_Api_Hint": "URL API (оставьте пустым для сервера по умолчанию):",
        "Settings_About_Title": "О приложении",
        "Settings_About_Build": "Сборка",
        "Settings_About_Publisher": "Издатель",
        "Settings_About_Platform": "Платформа",
        "Settings_Close": "Закрыть",
        "Nav_Verifier": "Проверка по QR",
        // Web dashboard menu parity (Sidebar.tsx nav.* keys).
        "Nav_MyId": "Моё удостоверение",
        "Nav_Logs": "История событий",
        "Nav_Devices": "Доверенные устройства",
        "Nav_Security": "Безопасность",
        "Nav_TokenReader": "Считыватель токена",
        "Nav_MyOrganizations": "Мои организации",
        "Nav_Children": "Мои дети",
        "Nav_Sign": "Подпись",
        "Nav_Support": "Поддержка",
        "Common_User": "Пользователь",
        "Update_LastChecked": "Проверено",
        "Update_Available": "Доступно обновление",
        "Home_Hero_Title": "PetroNet — электронное удостоверение личности Монголии",
        "Dashboard_Device_Registered": "Зарегистрировано",
        "Dashboard_Wordmark": "NATIONAL ID",
        "Common_Loading": "Загрузка...",
        "Common_Checking": "Проверка...",
        "Org_RegNumber_Hint": "Введите регистрационный номер организации.",
        "Org_List_Empty_Hint": "Зарегистрируйте организацию и добавьте подписантов.",
        "Org_Members_Empty": "Нет участников",
        "Org_Reg_Short": "Рег. №",
        "Org_Sign_Waiting": "Запрос на подтверждение отправлен в приложение e-ID Mongolia на вашем телефоне",
        "Login_Left_Subtitle": "Система цифрового удостоверения личности",
        "Login_Left_Safe": "Безопасно",
        "Login_Left_Reliable": "Надёжно",
        "Login_Left_Description": "Единая система входа Монголии для цифрового удостоверения гражданина.",
        "Login_NationalId_PushHint": "Введите регистрационный номер или номер гражданской регистрации. Уведомление придёт в приложение e-ID Mongolia на вашем телефоне.",
        "Login_Token_Connected": "Подключённый токен",
        "Login_Result_KycLabel": "Уровень KYC",
        "Common_Refresh": "Обновить",
        "Common_Details": "Подробнее",
        "Common_Cancel": "Отмена",
        "Tokens_Connected_Header": "Подключённые токены",
        "Tokens_Empty_Title": "Токен не найден.",
        "Tokens_Empty_Hint": "Подключите USB-токен и нажмите «Обновить».",
        "Tokens_Default_Name": "Токен FEITIAN",
        "Tokens_Connected": "Подключён",
        "Tokens_Disconnected": "Отключён",
        "Tokens_Ready": "USB-токен готов",
        "Tokens_PlugIn": "Подключите USB-токен",
        "Tokens_Disconnected_Notice": "Токен был отключён. Подключите USB-токен снова.",
        "Tokens_Info": "Информация",
        "Tokens_Info_Name": "Название",
        "Tokens_Info_Fips": "Режим FIPS",
        "Tokens_Info_Atr": "ATR",
        "Tokens_Yes": "Да",
        "Tokens_No": "Нет",
        "Tokens_Section_Provision": "Настройка токена",
        "Tokens_Section_Csr": "CSR → сертификат (отправить на сервер)",
        "Tokens_Section_SignTest": "Тест подписи",
        "Tokens_Section_ChangePin": "Смена PIN",
        "Tokens_Section_UnlockPin": "Разблокировка PIN (нужен SO PIN)",
        "Tokens_Section_ChangeSoPin": "Смена админского (SO) PIN",
        "Tokens_ChangePin_Current": "Текущий PIN",
        "Tokens_ChangePin_New": "Новый PIN",
        "Tokens_ChangePin_Confirm": "Повторите новый PIN",
        "Tokens_SoPin_Current": "Текущий SO PIN",
        "Tokens_SoPin_New": "Новый SO PIN",
        "Tokens_SoPin_Confirm": "Повторите новый SO PIN",
        "Tokens_Unlock_SoPin": "Админский (SO) PIN",
        "Tokens_Unlock_New": "Новый пользовательский PIN",
        "Tokens_Unlock_Confirm": "Повторите новый пользовательский PIN",
        "Tokens_ChangePin_Hint": "Обновляет PIN, которым разблокируются ключи токена.",
        "Tokens_UnlockPin_Hint": "Если пользовательский PIN заблокирован из-за многократного неверного ввода, разблокируйте его админским (SO) PIN и задайте новый PIN.",
        "Tokens_ChangeSoPin_Hint": "Обновляет админский PIN, используемый для настройки токена и разблокировки PIN-кодов.",
        "Tokens_ChangePin_Action": "Сменить PIN",
        "Tokens_UnlockPin_Action": "Разблокировать PIN",
        "Tokens_ChangeSoPin_Action": "Сменить SO PIN",
        "Verifier_Subtitle": "Подключите USB-сканер QR и отсканируйте «Мой QR» в приложении гражданина. После сканирования гражданин подтверждает операцию PIN-кодом на телефоне.",
        "Verifier_ScanField_Label": "Поле сканирования",
        "Verifier_ScanField_Placeholder": "Установите фокус сюда и отсканируйте QR…",
        "Verifier_Sending": "Отправка…",
        "Verifier_Running": "Гражданин подтверждает на телефоне…",
        "Verifier_Code": "Код подтверждения:",
        "Verifier_Verified": "Подтверждено",
        "Verifier_Row_FullName": "Полное имя",
        "Verifier_Row_Surname": "Фамилия",
        "Verifier_Row_GivenName": "Имя",
        "Verifier_Row_CivilId": "Гражданский ID",
        "Verifier_Next": "Далее",
        "Verifier_Rescan": "Сканировать снова",
        "Verifier_Error_Expired": "Сессия истекла. Отсканируйте ещё раз.",
        "Verifier_Error_Refused": "Гражданин отклонил запрос.",
        "Verifier_Error_Timeout": "Время ожидания ответа истекло.",
        "Verifier_Error_Generic": "Ошибка: недействительный QR-код или сбой сети.",
        "Sign_Field_NationalId": "Регистрационный номер",
        "Sign_Field_DocName": "Название документа",
        "Sign_PickFile": "Выбрать файл…",
        "Sign_HashReady": "Хеш готов",
        "Sign_Action": "Подписать",
        "Sign_Success": "Успешно",
        "Sign_Copy": "Копировать",
        "Sign_KeyLabel": "Метка ключа",
        "Tokens_Objects_Section": "Объекты токена",
        "Tokens_Objects_Pin": "PIN токена",
        "Tokens_Objects_Load": "Загрузить объекты",
        "Tokens_Objects_Import": "Импортировать сертификат",
        "Tokens_Objects_Delete": "Удалить",
        "Tokens_Objects_Empty": "На токене нет объектов (или они ещё не загружены).",
        "Tokens_GenKey_Section": "Создание ключа подписи",
        "Tokens_GenKey_Hint": "Создать на токене пару ключей EC P-256 (ключ подписи для CSR / выпуска сертификата).",
        "Tokens_GenKey_Action": "Создать ключ",
    ]
    private static let extraZh: [String: String] = [
        "Settings_Language_Hint": "语言会立即切换。",
        "Settings_Startup_Title": "启动",
        "Settings_Startup_LaunchAtLogin": "登录时自动打开",
        "Settings_Startup_BackgroundMode": "菜单栏模式（隐藏 Dock 图标）",
        "Settings_Startup_Hint": "在菜单栏模式下，应用仅在顶部菜单栏中运行 —— 关闭窗口后它仍会继续运行。",
        "MenuBar_Open": "打开窗口",
        "MenuBar_Logout": "退出登录",
        "MenuBar_Quit": "退出 PetroNet",
        "MenuBar_SignedIn": "已登录",
        "MenuBar_SignedOut": "未登录",
        "Settings_Api_Title": "服务器",
        "Settings_Api_Hint": "API 地址（留空则使用默认服务器）：",
        "Settings_About_Title": "关于",
        "Settings_About_Build": "构建版本",
        "Settings_About_Publisher": "发布者",
        "Settings_About_Platform": "平台",
        "Settings_Close": "关闭",
        "Nav_Verifier": "二维码验证",
        // Web dashboard menu parity (Sidebar.tsx nav.* keys).
        "Nav_MyId": "我的身份",
        "Nav_Logs": "操作记录",
        "Nav_Devices": "受信任设备",
        "Nav_Security": "安全",
        "Nav_TokenReader": "令牌读取器",
        "Nav_MyOrganizations": "我的组织",
        "Nav_Children": "我的子女",
        "Nav_Sign": "电子签名",
        "Nav_Support": "技术支持",
        "Common_User": "用户",
        "Update_LastChecked": "已检查",
        "Update_Available": "有可用更新",
        "Home_Hero_Title": "PetroNet —— 蒙古国电子身份证",
        "Dashboard_Device_Registered": "注册时间",
        "Dashboard_Wordmark": "NATIONAL ID",
        "Common_Loading": "加载中...",
        "Common_Checking": "检查中...",
        "Org_RegNumber_Hint": "请输入组织的登记号。",
        "Org_List_Empty_Hint": "注册您的组织并添加数字签署人。",
        "Org_Members_Empty": "暂无成员",
        "Org_Reg_Short": "登记号",
        "Org_Sign_Waiting": "确认请求已发送至您手机上的 e-ID Mongolia 应用",
        "Login_Left_Subtitle": "公民数字身份系统",
        "Login_Left_Safe": "安全",
        "Login_Left_Reliable": "可靠",
        "Login_Left_Description": "蒙古国公民电子身份证的统一登录系统。",
        "Login_NationalId_PushHint": "请输入登记号或公民登记号。您手机上的 e-ID Mongolia 应用将收到通知。",
        "Login_Token_Connected": "已连接的令牌",
        "Login_Result_KycLabel": "KYC 等级",
        "Common_Refresh": "刷新",
        "Common_Details": "详情",
        "Common_Cancel": "取消",
        "Tokens_Connected_Header": "已连接的令牌",
        "Tokens_Empty_Title": "未找到令牌。",
        "Tokens_Empty_Hint": "请插入 USB 令牌并点击“刷新”。",
        "Tokens_Default_Name": "FEITIAN 令牌",
        "Tokens_Connected": "已连接",
        "Tokens_Disconnected": "未连接",
        "Tokens_Ready": "USB 令牌就绪",
        "Tokens_PlugIn": "请插入 USB 令牌",
        "Tokens_Disconnected_Notice": "令牌已断开。请重新插入 USB 令牌。",
        "Tokens_Info": "信息",
        "Tokens_Info_Name": "名称",
        "Tokens_Info_Fips": "FIPS 模式",
        "Tokens_Info_Atr": "ATR",
        "Tokens_Yes": "是",
        "Tokens_No": "否",
        "Tokens_Section_Provision": "配置令牌",
        "Tokens_Section_Csr": "CSR → 证书（提交至后端）",
        "Tokens_Section_SignTest": "签名测试",
        "Tokens_Section_ChangePin": "修改 PIN",
        "Tokens_Section_UnlockPin": "解锁 PIN（需要 SO PIN）",
        "Tokens_Section_ChangeSoPin": "修改管理员（SO）PIN",
        "Tokens_ChangePin_Current": "当前 PIN",
        "Tokens_ChangePin_New": "新 PIN",
        "Tokens_ChangePin_Confirm": "确认新 PIN",
        "Tokens_SoPin_Current": "当前 SO PIN",
        "Tokens_SoPin_New": "新 SO PIN",
        "Tokens_SoPin_Confirm": "确认新 SO PIN",
        "Tokens_Unlock_SoPin": "管理员（SO）PIN",
        "Tokens_Unlock_New": "新用户 PIN",
        "Tokens_Unlock_Confirm": "确认新用户 PIN",
        "Tokens_ChangePin_Hint": "更新用于解锁令牌密钥的 PIN 码。",
        "Tokens_UnlockPin_Hint": "若用户 PIN 因多次输错而被锁定，可使用管理员（SO）PIN 解锁并设置新的 PIN。",
        "Tokens_ChangeSoPin_Hint": "更新用于配置令牌与解锁 PIN 的管理员 PIN 码。",
        "Tokens_ChangePin_Action": "修改 PIN",
        "Tokens_UnlockPin_Action": "解锁 PIN",
        "Tokens_ChangeSoPin_Action": "修改 SO PIN",
        "Verifier_Subtitle": "请插入 USB 二维码扫描器，扫描公民应用中的“我的二维码”。扫描后，公民在手机上输入 PIN 完成确认。",
        "Verifier_ScanField_Label": "扫描输入框",
        "Verifier_ScanField_Placeholder": "请将光标置于此处并扫描二维码…",
        "Verifier_Sending": "发送中…",
        "Verifier_Running": "公民正在手机上确认…",
        "Verifier_Code": "验证码：",
        "Verifier_Verified": "已验证",
        "Verifier_Row_FullName": "全名",
        "Verifier_Row_Surname": "姓",
        "Verifier_Row_GivenName": "名",
        "Verifier_Row_CivilId": "公民号",
        "Verifier_Next": "下一位",
        "Verifier_Rescan": "重新扫描",
        "Verifier_Error_Expired": "会话已过期，请重新扫描。",
        "Verifier_Error_Refused": "公民已拒绝。",
        "Verifier_Error_Timeout": "等待响应超时。",
        "Verifier_Error_Generic": "错误：二维码无效或网络故障。",
        "Sign_Field_NationalId": "登记号",
        "Sign_Field_DocName": "文件名称",
        "Sign_PickFile": "选择文件…",
        "Sign_HashReady": "哈希已就绪",
        "Sign_Action": "签名",
        "Sign_Success": "成功",
        "Sign_Copy": "复制",
        "Sign_KeyLabel": "密钥标签",
        "Tokens_Objects_Section": "令牌内的对象",
        "Tokens_Objects_Pin": "令牌 PIN",
        "Tokens_Objects_Load": "加载对象",
        "Tokens_Objects_Import": "导入证书",
        "Tokens_Objects_Delete": "删除",
        "Tokens_Objects_Empty": "令牌上没有对象（或尚未加载）。",
        "Tokens_GenKey_Section": "生成签名密钥",
        "Tokens_GenKey_Hint": "在令牌上创建 EC P-256 密钥对（用于 CSR / 证书签发的签名密钥）。",
        "Tokens_GenKey_Action": "生成密钥",
    ]
}
