/**
 * fr overlay for the ai app.
 *
 * Generated by `npm run i18n:translate -- --locale fr`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/ai.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const fr: Record<string, string> = {
  "ai.action.add_knowledge": "Ajouter une connaissance",
  "ai.action.listen": "Écouter",
  "ai.field.knowledge_content": "Informations vérifiées que l'assistant AI peut utiliser",
  "ai.field.knowledge_title": "Titre",
  "ai.field.source_url": "URL source",
  "ai.field.target_language": "Langue cible",
  "ai.message.greeting": "Bonjour. Interrogez-moi sur les données de votre organisation, le stock, les contacts ou le fonctionnement du système.",
  "ai.message.knowledge_added": "La connaissance a été ajoutée",
  "ai.message.microphone_denied": "Le microphone n'est pas disponible.",
  "ai.message.processing": "L'assistant AI traite…",
  "ai.message.prompt_saved": "L'invite AI a été enregistrée",
  "ai.message.voice_message": "🎙 Message vocal",
  "ai.scope.global": "Par défaut",
  "ai.scope.tenant": "Du tenant",
  "ai.view.engine_note": "Gemini · outils de plateforme sécurisés pour le tenant",
  "ai.view.knowledge": "Base de connaissances",
  "ai.view.placeholder": "Demander à l'IA...",
  "ai.view.settings_subtitle": "Gérer le périmètre de réponse, les instructions et la base de connaissances de l'assistant AI de ce tenant.",
  "ai.view.settings_title": "Paramètres de l'IA",
  "ai.view.subtitle": "Assistant IA {brand}",
  "ai.view.system_prompt": "Invite système",
  "ai.view.tab_chat": "Chat AI",
  "ai.view.tab_translate": "Traduction",
  "ai.view.title": "Copilote IA",
  "ai.view.translate_placeholder": "Texte à traduire…",
};
