/**
 * fr overlay for the integrations app.
 *
 * Generated by `npm run i18n:translate -- --locale fr`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/integrations.ts,
 * which hands it to registerDictionary; nothing in the core names it. It was
 * part of this locale's core.ts until 2026-08-27, when the connectors became an
 * app in client-gerege-nexus.
 */
export const fr: Record<string, string> = {
  "integrations.action.connect": "Connecter",
  "integrations.action.create": "Ajouter une intégration",
  "integrations.action.disconnect": "Déconnecter",
  "integrations.action.register": "Enregistrer le connecteur",
  "integrations.field.auto_export": "Classer automatiquement ici chaque document nouvellement signé",
  "integrations.field.calendar_id": "ID du calendrier (facultatif)",
  "integrations.field.connected_account": "Compte connecté",
  "integrations.field.drive_folder": "ID du dossier de destination (facultatif)",
  "integrations.field.drive_folder_placeholder": "vide signifie la racine du Drive",
  "integrations.field.dropbox_folder": "Chemin du dossier de destination (facultatif)",
  "integrations.field.dropbox_folder_placeholder": "ex. Contrats/2026",
  "integrations.field.name": "Nom de l'intégration",
  "integrations.field.name_placeholder": "ex: Webhook de ventes",
  "integrations.field.secret": "Clé secrète (Signature)",
  "integrations.field.secret_placeholder": "Clé secrète HMAC facultative",
  "integrations.field.target_url": "URL du point de terminaison cible",
  "integrations.field.type": "Type d'intégration",
  "integrations.message.auto_export_on": "Classement automatique activé",
  "integrations.message.confirm_delete": "Supprimer l'intégration {name} ?",
  "integrations.message.connect_after_save": "Après l'enregistrement, utilisez Connecter pour autoriser le compte.",
  "integrations.message.connect_failed": "Impossible de connecter le compte",
  "integrations.message.connected": "{name} est connecté.",
  "integrations.message.delete_failed": "Échec de la suppression de l'intégration",
  "integrations.message.disconnect_failed": "Impossible de déconnecter le compte",
  "integrations.message.empty": "Aucune intégration enregistrée.",
  "integrations.message.encryption_missing": "INTEGRATION_ENCRYPTION_KEY n'est pas défini : les secrets et les connexions de compte ne peuvent pas être stockés.",
  "integrations.message.load_failed": "Impossible de charger les intégrations",
  "integrations.message.loading": "Chargement des intégrations...",
  "integrations.message.meet_via_calendar": "Un lien Meet est émis via Calendar, ce connecteur demande donc l'accès au calendrier.",
  "integrations.message.not_connected": "Aucun compte connecté",
  "integrations.message.register_failed": "Échec de l'enregistrement de l'intégration",
  "integrations.state.unavailable": "indisponible",
  "integrations.type.custom_rest": "Point de terminaison REST personnalisé",
  "integrations.type.dropbox": "Dropbox",
  "integrations.type.google_drive": "Google Drive",
  "integrations.type.google_meet": "Google Meet",
  "integrations.type.government_gateway": "Passerelle gouvernementale",
  "integrations.type.payment_gateway": "Passerelle de paiement",
  "integrations.type.webhook": "Récepteur Webhook",
  "integrations.view.create_title": "Enregistrer un connecteur d'intégration",
  "integrations.view.subtitle": "Gérez les passerelles gouvernementales, les connecteurs REST API et les webhooks d'événements",
  "integrations.view.title": "Intégrations de systèmes externes et Webhooks",
};
