/**
 * fr overlay for the storefront app.
 *
 * Generated by `npm run i18n:translate -- --locale fr`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/storefront.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const fr: Record<string, string> = {
  "storefront.action.browse": "Parcourir le catalogue",
  "storefront.action.publish": "Publier une application",
  "storefront.category.other": "Autre",
  "storefront.stat.apps": "applications",
  "storefront.stat.categories": "catégories",
  "storefront.stat.publishers": "éditeurs",
  "storefront.view.catalogue_eyebrow": "CATALOGUE",
  "storefront.view.catalogue_lede": "L'administrateur d'une instance les installe depuis son propre écran App Store. Chaque version est distribuée par le catalogue signé.",
  "storefront.view.catalogue_title": "Applications publiées",
  "storefront.view.eyebrow": "GEREGE APP STORE · CATALOGUE OUVERT",
  "storefront.view.lede": "Le catalogue officiel des applications qui fonctionnent sur {brand}. Chaque application arrive avec un manifeste signé, si bien qu'une instance peut vérifier ce qu'elle installe.",
  "storefront.view.title_highlight": "une application à la fois",
  "storefront.view.title_lead": "Tout ce qu'une organisation utilise,",
};
