"use client";

import {useMemo,useState} from "react";
import {api} from "@/lib/api";
import {useLoadOnMount} from "@/lib/useResource";
import {Activity,Copy,KeyRound,MonitorCog,RefreshCw,ShieldCheck,WifiOff} from "lucide-react";

type Device={id:string;name:string;platform:string;form_factor:string;site:string;status:string;app_version:string;os_version:string;last_seen_at?:string;enrolled_at:string};
type Member={membership_id:string;name:string;email:string};

export default function DeviceFleetPage(){
  const [devices,setDevices]=useState<Device[]>([]),[members,setMembers]=useState<Member[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [code,setCode]=useState<{value:string;expires:string}|null>(null),[pin,setPin]=useState(""),[member,setMember]=useState("");
  async function load(){setLoading(true);setError("");try{const [fleet,access]=await Promise.all([api.getDevices(),api.getAccessOverview()]);setDevices(fleet.devices);setMembers(access.members);setMember(v=>v||access.members[0]?.membership_id||"")}catch(e){setError(e instanceof Error?e.message:"Төхөөрөмжийн парк ачаалсангүй")}finally{setLoading(false)}}
  useLoadOnMount(load);
  const now=Date.now(),online=devices.filter(d=>d.last_seen_at&&now-new Date(d.last_seen_at).getTime()<5*60_000).length;
  const groups=useMemo(()=>Object.entries(devices.reduce<Record<string,Device[]>>((all,d)=>{(all[d.site||"Байршилгүй"]??=[]).push(d);return all},{})),[devices]);
  async function issue(){setError("");try{const result=await api.createDeviceEnrollmentCode();setCode({value:result.code,expires:result.expires_at})}catch(e){setError(e instanceof Error?e.message:"Код үүсгэсэнгүй")}}
  async function savePin(){if(!member||!/^[0-9]{4,12}$/.test(pin))return;setError("");try{await api.setStaffPin(member,pin);setPin("");setNotice("Ажилтны PIN шинэчлэгдлээ");setTimeout(()=>setNotice(""),2500)}catch(e){setError(e instanceof Error?e.message:"PIN хадгалсангүй")}}
  if(loading)return <div className="p-8 text-sm text-slate-500">Төхөөрөмжийн паркийг шалгаж байна…</div>;
  return <div className="mx-auto w-full max-w-[1500px] space-y-6">
    <header className="grid gap-5 border-b border-slate-300 pb-6 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="font-mono text-[11px] font-bold uppercase tracking-[.22em] text-cyan-700">Fleet control / live registry</p><h1 className="mt-2 flex items-center gap-3 text-3xl font-black tracking-tight text-slate-950"><MonitorCog className="h-8 w-8 text-cyan-700"/>Төхөөрөмжийн парк</h1><p className="mt-2 max-w-2xl text-sm text-slate-600">Windows ба Android kiosk/POS, mobile client-үүдийн enrollment, төлөв, ажилтны хурдан нэвтрэлтийг нэг цэгээс удирдана.</p></div><button onClick={()=>void load()} className="flex items-center gap-2 rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-bold hover:border-cyan-700"><RefreshCw className="h-4 w-4"/>Дахин шалгах</button></header>
    {error&&<div className="border-l-4 border-red-600 bg-red-50 p-3 text-sm text-red-800">{error}</div>}{notice&&<div className="border-l-4 border-emerald-600 bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</div>}
    <section className="grid overflow-hidden rounded-md border border-slate-300 bg-slate-950 text-white sm:grid-cols-3"><Metric label="Нийт бүртгэл" value={devices.length} hint="device identity"/><Metric label="Сүүлийн 5 минутад" value={online} hint="online heartbeat"/><Metric label="Анхаарах" value={devices.filter(d=>d.status!=="ACTIVE"||!d.last_seen_at).length} hint="offline / inactive"/></section>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="space-y-5">{groups.length===0?<div className="rounded-md border border-dashed border-slate-400 bg-white p-10 text-center"><WifiOff className="mx-auto h-8 w-8 text-slate-400"/><h2 className="mt-3 font-bold">Бүртгэлтэй төхөөрөмж алга</h2><p className="mt-1 text-sm text-slate-500">Баруун талд нэг удаагийн код үүсгээд native Device Settings-д оруулна уу.</p></div>:groups.map(([site,items])=><div key={site} className="overflow-hidden rounded-md border border-slate-300 bg-white"><div className="flex items-center justify-between border-b border-slate-200 bg-slate-100 px-4 py-2"><h2 className="font-mono text-xs font-black uppercase tracking-wider text-slate-700">{site}</h2><span className="text-xs text-slate-500">{items.length} төхөөрөмж</span></div><div className="divide-y divide-slate-200">{items.map(d=><DeviceRow key={d.id} device={d} online={!!d.last_seen_at&&now-new Date(d.last_seen_at).getTime()<5*60_000}/>)}</div></div>)}</section>
      <aside className="space-y-5"><section className="rounded-md border border-cyan-800 bg-cyan-950 p-5 text-white"><div className="flex items-center gap-2"><KeyRound className="h-5 w-5 text-cyan-300"/><h2 className="font-bold text-white">Enrollment code</h2></div><p className="mt-2 text-xs leading-5 text-cyan-100">Код 10 минут, зөвхөн нэг удаа хүчинтэй. Device token буцааж харуулахгүй.</p>{code?<div className="mt-5"><button onClick={()=>void navigator.clipboard.writeText(code.value)} className="flex w-full items-center justify-between border-y border-cyan-700 py-4 font-mono text-xl font-black tracking-[.12em]"><span>{code.value}</span><Copy className="h-4 w-4"/></button><p className="mt-2 font-mono text-[10px] text-cyan-300">ДУУСАХ: {new Date(code.expires).toLocaleString()}</p></div>:null}<button onClick={()=>void issue()} className="mt-5 w-full rounded bg-cyan-300 px-4 py-3 text-sm font-black text-cyan-950 hover:bg-white">{code?"Шинэ код үүсгэх":"Код үүсгэх"}</button></section>
      <section className="rounded-md border border-slate-300 bg-white p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-slate-700"/><h2 className="font-bold">Ажилтны PIN</h2></div><p className="mt-2 text-xs leading-5 text-slate-500">POS/tablet дээр ажилтан хурдан солих 4–12 оронтой credential.</p><label className="mt-4 block text-xs font-bold text-slate-600">Ажилтан<select value={member} onChange={e=>setMember(e.target.value)} className="mt-1 w-full rounded border border-slate-300 bg-white px-3 py-2 text-sm">{members.map(m=><option key={m.membership_id} value={m.membership_id}>{m.name} · {m.email}</option>)}</select></label><label className="mt-3 block text-xs font-bold text-slate-600">Шинэ PIN<input type="password" inputMode="numeric" autoComplete="new-password" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,12))} className="mt-1 w-full rounded border border-slate-300 px-3 py-2 font-mono text-lg tracking-[.3em]"/></label><button disabled={!member||!/^[0-9]{4,12}$/.test(pin)} onClick={()=>void savePin()} className="mt-4 w-full rounded bg-slate-900 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40">PIN хадгалах</button></section></aside>
    </div>
  </div>
}
function Metric({label,value,hint}:{label:string;value:number;hint:string}){return <div className="border-b border-slate-700 p-5 last:border-0 sm:border-b-0 sm:border-r"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-slate-400">{label}</p><div className="mt-1 flex items-baseline gap-3"><strong className="text-4xl font-black tabular-nums">{value}</strong><span className="font-mono text-[10px] text-cyan-300">{hint}</span></div></div>}
function DeviceRow({device:d,online}:{device:Device;online:boolean}){function toggle(){void api.setDeviceStatus(d.id,d.status==="ACTIVE"?"DISABLED":"ACTIVE").then(()=>location.reload())}return <article className="grid gap-3 p-4 md:grid-cols-[12px_minmax(160px,1fr)_130px_1.2fr_auto] md:items-center"><span className={`h-3 w-3 rounded-full ${online?"bg-emerald-500 shadow-[0_0_0_4px_#d1fae5]":"bg-slate-300"}`}/><div><h3 className="font-bold text-slate-900">{d.name}</h3><code className="text-[10px] text-slate-500">{d.id}</code></div><div><span className="block font-mono text-[10px] font-bold uppercase text-cyan-800">{d.platform} / {d.form_factor}</span><button onClick={toggle} title="Төлөв солих" className={`mt-1 rounded px-2 py-1 text-[10px] font-black ${d.status==="ACTIVE"?"bg-emerald-100 text-emerald-800":"bg-slate-200 text-slate-700"}`}>{d.status}</button></div><div className="text-xs text-slate-600"><span className="block truncate">{d.os_version||"OS тодорхойгүй"}</span><span className="block truncate text-slate-400">App {d.app_version||"—"}</span></div><div className="text-right font-mono text-[10px] text-slate-500"><Activity className="mb-1 ml-auto h-4 w-4"/>{d.last_seen_at?new Date(d.last_seen_at).toLocaleString():"холбогдоогүй"}</div></article>}
