/*
 * Gerege Nexus
 * Copyright (c) 2026 Gerege Systems Development Team, Gerege Nomadica Foundation
 * Distributed under the Apache 2.0 License.
 */

// Generated by frontend/scripts/generate-icon-map.mjs — do not edit.
//
// Every icon named by a Go menu definition, a catalogue manifest or the shell's
// own search index. Run `npm run icons:generate` after changing any of those;
// CI runs it with --check and fails on a diff.

import type { LucideIcon } from "lucide-react";
import {
  Code2,
  FileText,
  Fuel,
  Grid,
  KeyRound,
  KeySquare,
  Landmark,
  Network,
  Palette,
  Route,
  ScrollText,
  Settings,
  ShieldCheck,
  Users,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  "code-2": Code2,
  "file-text": FileText,
  "fuel": Fuel,
  "grid": Grid,
  "key-round": KeyRound,
  "key-square": KeySquare,
  "landmark": Landmark,
  "network": Network,
  "palette": Palette,
  "route": Route,
  "scroll-text": ScrollText,
  "settings": Settings,
  "shield-check": ShieldCheck,
  "users": Users,
};
