import type { KioskResource } from "./types";

/**
 * Every kiosk screen, declared.
 *
 * Paths are the legacy routes exactly as the modules register them, quirks
 * included: the lookup groups nest inside /common, the work log inside /daily,
 * locations list from /location/list but write to /location, and translations
 * expose no update or delete because the module never implemented them.
 * Declaring the real surface rather than a tidied one is the point — a screen
 * offering an edit the API cannot perform is worse than no edit.
 *
 * Kiosk image assignments have no screen for the same reason: upstream wires
 * GET /image/kiosk to the create handler, so the module cannot list them.
 */

import type { KioskColumn, KioskField } from "./types";
import type { DictionaryKey } from "@/lib/i18n";

const F = (key: string, label: DictionaryKey, extra: Partial<KioskField> = {}): KioskField => ({ key, label, ...extra });
const C = (key: string, label: DictionaryKey, extra: Partial<KioskColumn> = {}): KioskColumn => ({ key, label, ...extra });

export const KIOSK_RESOURCES: KioskResource[] = [
  // ── Terminals and their devices ────────────────────────────────────────────
  {
    slug: "terminals",
    title: "kiosk.view.terminals",
    description: "kiosk.view.terminals_desc",
    icon: "monitor",
    list: "/terminal",
    create: "/terminal",
    update: "/terminal",
    remove: "/terminal",
    columns: [
      C("id", "kiosk.field.id"),
      C("name", "kiosk.field.name"),
      C("serial_no", "kiosk.field.serial"),
      C("location_name", "kiosk.field.location"),
      C("status_code", "kiosk.field.status"),
      C("owner", "kiosk.field.owner"),
    ],
    fields: [
      F("name", "kiosk.field.name", { required: true }),
      F("serial_no", "kiosk.field.serial"),
      F("type_code", "kiosk.field.type"),
      F("zone_code", "kiosk.field.zone"),
      F("status_code", "kiosk.field.status"),
      F("location_id", "kiosk.field.location_id", { type: "number" }),
      F("owner_id", "kiosk.field.owner_id", { type: "number" }),
      F("client_ip", "kiosk.field.client_ip"),
      F("mac_address", "kiosk.field.mac"),
    ],
  },
  {
    slug: "terminal-pinpads",
    title: "kiosk.view.pinpads",
    description: "kiosk.view.pinpads_desc",
    icon: "credit-card",
    list: "/terminal/pinpad",
    create: "/terminal/pinpad",
    update: "/terminal/pinpad",
    remove: "/terminal/pinpad",
    columns: [
      C("id", "kiosk.field.id"),
      C("name", "kiosk.field.name"),
      C("port", "kiosk.field.port"),
      C("bank_terminal_id", "kiosk.field.bank_terminal"),
      C("type_name", "kiosk.field.type"),
    ],
    fields: [
      F("name", "kiosk.field.name", { required: true }),
      F("port", "kiosk.field.port"),
      F("bank_terminal_id", "kiosk.field.bank_terminal"),
      F("type_code", "kiosk.field.type_code"),
    ],
  },
  {
    slug: "terminal-printers",
    title: "kiosk.view.printers",
    description: "kiosk.view.printers_desc",
    icon: "printer",
    list: "/terminal/printer",
    create: "/terminal/printer",
    update: "/terminal/printer",
    remove: "/terminal/printer",
    columns: [
      C("id", "kiosk.field.id"),
      C("name", "kiosk.field.name"),
      C("type_name", "kiosk.field.type"),
    ],
    fields: [
      F("name", "kiosk.field.name", { required: true }),
      F("type_code", "kiosk.field.type_code"),
    ],
  },
  {
    slug: "terminal-videos",
    title: "kiosk.view.terminal_videos",
    description: "kiosk.view.terminal_videos_desc",
    icon: "video",
    list: "/terminal/video/list",
    remove: "/terminal/video/delete",
    idKey: "file_id",
    media: { urlKey: "file_url" },
    columns: [
      C("file_id", "kiosk.field.id"),
      C("file_url", "kiosk.field.file"),
      C("terminals", "kiosk.field.terminals", {
        // The row carries the whole terminal record for each assignment;
        // rendering that raw fills the cell with JSON.
        render: (row) => (Array.isArray(row.terminals) ? row.terminals.length : 0),
      }),
      C("expires_date", "kiosk.field.expires"),
    ],
    readOnlyReason: "kiosk.message.upload_only_on_device",
  },
  {
    slug: "terminal-files",
    title: "kiosk.view.terminal_files",
    description: "kiosk.view.terminal_files_desc",
    icon: "files",
    list: "/terminal/file/list",
    media: { urlKey: "file_url", nameKey: "name" },
    columns: [
      C("id", "kiosk.field.id"),
      C("name", "kiosk.field.name"),
      C("created_at", "kiosk.field.created_at"),
      C("expires_date", "kiosk.field.expires"),
    ],
    readOnlyReason: "kiosk.message.cdn_backed",
  },
  {
    slug: "change-locations",
    title: "kiosk.view.change_locations",
    description: "kiosk.view.change_locations_desc",
    icon: "arrow-right-left",
    list: "/terminal/change_locations",
    columns: [
      C("id", "kiosk.field.id"),
      C("terminal_id", "kiosk.field.terminal"),
      C("location_name", "kiosk.field.location"),
      C("created_at", "kiosk.field.created_at"),
    ],
    readOnlyReason: "kiosk.message.audit_trail",
  },

  // ── Locations ──────────────────────────────────────────────────────────────
  {
    slug: "locations",
    title: "kiosk.view.locations",
    description: "kiosk.view.locations_desc",
    icon: "map-pin",
    list: "/location/list",
    create: "/location",
    update: "/location",
    remove: "/location",
    columns: [
      C("id", "kiosk.field.id"),
      C("name", "kiosk.field.name"),
      C("aimag_name", "kiosk.field.aimag"),
      C("sum_name", "kiosk.field.sum"),
      C("detail_text", "kiosk.field.description"),
    ],
    fields: [
      F("name", "kiosk.field.name", { required: true }),
      F("aimag_id", "kiosk.field.aimag_id", { type: "number" }),
      F("sum_id", "kiosk.field.sum_id", { type: "number" }),
      F("bag_id", "kiosk.field.bag_id", { type: "number" }),
      F("detail_text", "kiosk.field.description", { type: "textarea" }),
      F("longitude", "kiosk.field.longitude", { type: "number" }),
      F("latitude", "kiosk.field.latitude", { type: "number" }),
      F("employer", "kiosk.field.employer"),
      F("employer_phone", "kiosk.field.phone"),
      F("start_time", "kiosk.field.start_time"),
      F("end_time", "kiosk.field.end_time"),
    ],
  },
  {
    slug: "kiosk-locations",
    title: "kiosk.view.kiosk_locations",
    description: "kiosk.view.kiosk_locations_desc",
    icon: "map-pin",
    list: "/kiosklocation",
    create: "/kiosklocation",
    update: "/kiosklocation",
    remove: "/kiosklocation",
    columns: [
      C("id", "kiosk.field.id"),
      C("kiosk_name", "kiosk.field.name"),
      C("location_name", "kiosk.field.location"),
      C("aimag_name", "kiosk.field.aimag"),
      C("is_visible", "kiosk.field.visible"),
    ],
    fields: [
      F("terminal_id", "kiosk.field.terminal", { type: "number", required: true }),
      F("kiosk_name", "kiosk.field.name", { required: true }),
      F("location_name", "kiosk.field.location"),
      F("aimag_id", "kiosk.field.aimag_id", { type: "number" }),
      F("sum_id", "kiosk.field.sum_id", { type: "number" }),
      F("latitude", "kiosk.field.latitude", { type: "number" }),
      F("longitude", "kiosk.field.longitude", { type: "number" }),
      F("schedule", "kiosk.field.schedule"),
      F("description", "kiosk.field.description", { type: "textarea" }),
      F("is_visible", "kiosk.field.visible", { type: "boolean" }),
    ],
  },
  {
    slug: "countries",
    app: "kiosk-directory",
    title: "kiosk.view.countries",
    description: "kiosk.view.countries_desc",
    icon: "landmark",
    list: "/countries",
    idKey: "code",
    columns: [
      C("code", "kiosk.field.code"),
      C("iso_alpha_code_3", "kiosk.field.iso3"),
      C("common_name", "kiosk.field.name"),
      C("en_name", "kiosk.field.en_name"),
    ],
    readOnlyReason: "kiosk.message.reference_data",
  },

  // ── Commerce ───────────────────────────────────────────────────────────────
  {
    slug: "purchases",
    title: "kiosk.view.purchases",
    description: "kiosk.view.purchases_desc",
    icon: "shopping-cart",
    list: "/purchase",
    create: "/purchase",
    update: "/purchase",
    remove: "/purchase",
    columns: [
      C("id", "kiosk.field.id"),
      C("name", "kiosk.field.name"),
      C("reg_no", "kiosk.field.reg_no"),
      C("terminal_name", "kiosk.field.terminal"),
      C("purchase_type", "kiosk.field.type"),
      C("pre_amount", "kiosk.field.amount"),
      C("is_payment_name", "kiosk.field.status"),
    ],
    fields: [
      F("name", "kiosk.field.name", { required: true }),
      F("reg_no", "kiosk.field.reg_no"),
      F("phone_no", "kiosk.field.phone"),
      F("terminal_id", "kiosk.field.terminal", { type: "number" }),
      F("purchase_type_id", "kiosk.field.type", { type: "number" }),
      F("pre_amount", "kiosk.field.amount", { type: "number" }),
      F("remain_amount", "kiosk.field.remain_amount", { type: "number" }),
      F("start_contract_date", "kiosk.field.date", { type: "date" }),
      F("description", "kiosk.field.description", { type: "textarea" }),
    ],
  },
  {
    slug: "purchase-culture",
    title: "kiosk.view.culture",
    description: "kiosk.view.culture_desc",
    icon: "landmark",
    list: "/purchase/culture",
    columns: [C("id", "kiosk.field.id"), C("name", "kiosk.field.name")],
    readOnlyReason: "kiosk.message.reference_data",
  },
  {
    slug: "rates",
    title: "kiosk.view.rates",
    description: "kiosk.view.rates_desc",
    icon: "activity",
    list: "/rate",
    create: "/rate",
    columns: [
      C("terminal_id", "kiosk.field.terminal"),
      C("kiosk_name", "kiosk.field.name"),
      C("module_name", "kiosk.field.module"),
      C("score", "kiosk.field.score"),
      C("question_name", "kiosk.field.question"),
      C("created_at", "kiosk.field.created_at"),
    ],
    fields: [
      F("terminal_id", "kiosk.field.terminal", { required: true }),
      F("module_name", "kiosk.field.module"),
      F("service_id", "kiosk.field.service", { type: "number" }),
      F("score", "kiosk.field.score", { type: "number", required: true }),
      F("question_id", "kiosk.field.question", { type: "number" }),
    ],
  },
  {
    slug: "payment-types",
    title: "kiosk.view.payment_types",
    description: "kiosk.view.payment_types_desc",
    icon: "credit-card",
    list: "/payment_type",
    create: "/payment_type",
    update: "/payment_type",
    remove: "/payment_type",
    columns: [
      C("id", "kiosk.field.id"),
      C("name", "kiosk.field.name"),
      C("image", "kiosk.field.image"),
      C("status", "kiosk.field.status"),
    ],
    fields: [
      F("name", "kiosk.field.name", { required: true }),
      F("image", "kiosk.field.image"),
      F("status", "kiosk.field.status"),
    ],
  },

  // ── Daily control ──────────────────────────────────────────────────────────
  {
    slug: "daily-services",
    title: "kiosk.view.daily_services",
    description: "kiosk.view.daily_services_desc",
    icon: "server-cog",
    list: "/service",
    create: "/service",
    update: "/service",
    remove: "/service",
    columns: [
      C("id", "kiosk.field.id"),
      C("org_name", "kiosk.field.organization"),
      C("service_name", "kiosk.field.name"),
      C("service_type", "kiosk.field.type"),
      C("amount", "kiosk.field.amount"),
      C("status", "kiosk.field.status"),
    ],
    fields: [
      F("org_name", "kiosk.field.organization"),
      F("service_name", "kiosk.field.name", { required: true }),
      F("category_name", "kiosk.field.category"),
      F("service_type", "kiosk.field.type"),
      F("amount", "kiosk.field.amount", { type: "number" }),
      F("gerege_fee", "kiosk.field.gerege_fee", { type: "number" }),
      F("bank_fee", "kiosk.field.bank_fee", { type: "number" }),
      F("employer_name", "kiosk.field.employer"),
      F("status", "kiosk.field.status"),
      F("description", "kiosk.field.description", { type: "textarea" }),
    ],
  },
  {
    slug: "daily-paper",
    title: "kiosk.view.paper",
    description: "kiosk.view.paper_desc",
    icon: "files",
    list: "/paper",
    create: "/paper",
    update: "/paper",
    remove: "/paper",
    columns: [
      C("id", "kiosk.field.id"),
      C("terminal_id", "kiosk.field.terminal"),
      C("type_name", "kiosk.field.type"),
      C("count", "kiosk.field.count"),
      C("created_at", "kiosk.field.created_at"),
    ],
    fields: [
      F("terminal_id", "kiosk.field.terminal", { type: "number", required: true }),
      F("type_id", "kiosk.field.type", { type: "number" }),
      F("count", "kiosk.field.count", { type: "number" }),
      F("description", "kiosk.field.description", { type: "textarea" }),
    ],
  },
  {
    slug: "daily-toner",
    title: "kiosk.view.toner",
    description: "kiosk.view.toner_desc",
    icon: "printer",
    list: "/toner",
    create: "/toner",
    update: "/toner",
    remove: "/toner",
    columns: [
      C("id", "kiosk.field.id"),
      C("terminal_id", "kiosk.field.terminal"),
      C("type_name", "kiosk.field.type"),
      C("count", "kiosk.field.count"),
      C("created_at", "kiosk.field.created_at"),
    ],
    fields: [
      F("terminal_id", "kiosk.field.terminal", { type: "number", required: true }),
      F("type_id", "kiosk.field.type", { type: "number" }),
      F("count", "kiosk.field.count", { type: "number" }),
      F("description", "kiosk.field.description", { type: "textarea" }),
    ],
  },
  {
    slug: "daily-technical",
    title: "kiosk.view.technical",
    description: "kiosk.view.technical_desc",
    icon: "server-cog",
    list: "/daily/technical",
    create: "/daily/technical",
    update: "/daily/technical",
    remove: "/daily/technical",
    columns: [
      C("id", "kiosk.field.id"),
      C("terminal_id", "kiosk.field.terminal"),
      C("description", "kiosk.field.description"),
      C("created_at", "kiosk.field.created_at"),
    ],
    fields: [
      F("terminal_id", "kiosk.field.terminal", { type: "number" }),
      F("description", "kiosk.field.description", { type: "textarea" }),
    ],
  },
  {
    slug: "daily-sales",
    title: "kiosk.view.sales",
    description: "kiosk.view.sales_desc",
    icon: "chart-column",
    list: "/daily/sales",
    create: "/daily/sales",
    update: "/daily/sales",
    remove: "/daily/sales",
    columns: [
      C("id", "kiosk.field.id"),
      C("terminal_id", "kiosk.field.terminal"),
      C("description", "kiosk.field.description"),
      C("created_at", "kiosk.field.created_at"),
    ],
    fields: [
      F("terminal_id", "kiosk.field.terminal", { type: "number" }),
      F("description", "kiosk.field.description", { type: "textarea" }),
    ],
  },
  {
    slug: "work",
    title: "kiosk.view.work",
    description: "kiosk.view.work_desc",
    icon: "list-checks",
    list: "/daily/work",
    columns: [
      C("id", "kiosk.field.id"),
      C("terminal_id", "kiosk.field.terminal"),
      C("description", "kiosk.field.description"),
      C("created_at", "kiosk.field.created_at"),
    ],
    readOnlyReason: "kiosk.message.read_only_endpoint",
  },

  // ── Media ──────────────────────────────────────────────────────────────────
  {
    slug: "images",
    title: "kiosk.view.images",
    description: "kiosk.view.images_desc",
    icon: "image",
    list: "/image",
    create: "/image",
    update: "/image",
    remove: "/image",
    media: { urlKey: "file", nameKey: "name" },
    columns: [
      C("id", "kiosk.field.id"),
      C("name", "kiosk.field.name"),
      C("kiosk_type", "kiosk.field.type"),
      C("created_at", "kiosk.field.created_at"),
    ],
    fields: [
      F("name", "kiosk.field.name", { required: true }),
      F("file", "kiosk.field.url", { required: true }),
      F("kiosk_type", "kiosk.field.type"),
    ],
  },
  {
    slug: "videos",
    title: "kiosk.view.videos",
    description: "kiosk.view.videos_desc",
    icon: "video",
    list: "/video/list",
    columns: [
      C("id", "kiosk.field.id"),
      C("name", "kiosk.field.name"),
      C("url", "kiosk.field.url"),
    ],
    readOnlyReason: "kiosk.message.mms_backed",
  },

  // ── Logs ───────────────────────────────────────────────────────────────────
  {
    slug: "logs",
    title: "kiosk.view.logs",
    description: "kiosk.view.logs_desc",
    icon: "scroll-text",
    list: "/log/",
    columns: [
      C("id", "kiosk.field.id"),
      C("method", "kiosk.field.method"),
      C("path", "kiosk.field.path"),
      C("http_status_code", "kiosk.field.status"),
      C("created_date", "kiosk.field.created_at"),
    ],
    readOnlyReason: "kiosk.message.audit_trail",
  },
  {
    slug: "speech-logs",
    title: "kiosk.view.chimege",
    description: "kiosk.view.chimege_desc",
    icon: "activity",
    list: "/chimegelog",
    create: "/chimegelog",
    columns: [
      C("id", "kiosk.field.id"),
      C("terminal_id", "kiosk.field.terminal"),
      C("text", "kiosk.field.text"),
      C("created_at", "kiosk.field.created_at"),
    ],
    fields: [
      F("terminal_id", "kiosk.field.terminal", { type: "number" }),
      F("text", "kiosk.field.text", { type: "textarea" }),
    ],
  },

  // ── Reporting ──────────────────────────────────────────────────────────────
  {
    slug: "reports",
    title: "kiosk.view.reports",
    description: "kiosk.view.reports_desc",
    icon: "chart-column",
    list: "/report/aimag",
    columns: [
      C("id", "kiosk.field.id"),
      C("name", "kiosk.field.aimag"),
      C("aimag_code", "kiosk.field.code"),
      C("sum_count", "kiosk.field.count"),
    ],
    readOnlyReason: "kiosk.message.derived_data",
  },

  // ── Content and reference ──────────────────────────────────────────────────
  {
    slug: "menu-templates",
    title: "kiosk.view.menu_templates",
    description: "kiosk.view.menu_templates_desc",
    icon: "layout-template",
    list: "/menu-template",
    create: "/menu-template",
    update: "/menu-template",
    remove: "/menu-template",
    columns: [C("id", "kiosk.field.id"), C("name", "kiosk.field.name")],
    fields: [
      F("name", "kiosk.field.name", { required: true }),
      F("menu_body", "kiosk.field.menu_body", { type: "json", placeholder: "{ }" }),
    ],
  },
  {
    slug: "languages",
    title: "kiosk.view.languages",
    description: "kiosk.view.languages_desc",
    icon: "languages",
    list: "/lang",
    create: "/lang",
    update: "/lang",
    remove: "/lang",
    columns: [
      C("id", "kiosk.field.id"),
      C("code", "kiosk.field.code"),
      C("name", "kiosk.field.name"),
      C("status", "kiosk.field.status"),
    ],
    fields: [
      F("code", "kiosk.field.code", { required: true }),
      F("name", "kiosk.field.name", { required: true }),
      F("image", "kiosk.field.image"),
      F("status", "kiosk.field.status"),
    ],
  },
  {
    slug: "translation-keys",
    title: "kiosk.view.keys",
    description: "kiosk.view.keys_desc",
    icon: "key-round",
    list: "/key",
    create: "/key",
    update: "/key",
    remove: "/key",
    columns: [C("id", "kiosk.field.id"), C("code", "kiosk.field.code")],
    fields: [F("code", "kiosk.field.code", { required: true })],
  },
  {
    slug: "translations",
    title: "kiosk.view.translations",
    description: "kiosk.view.translations_desc",
    icon: "languages",
    list: "/translation",
    create: "/translation",
    columns: [
      C("id", "kiosk.field.id"),
      C("key_id", "kiosk.field.key"),
      C("lang_id", "kiosk.field.language"),
      C("text", "kiosk.field.text"),
    ],
    fields: [
      F("key_id", "kiosk.field.key", { type: "number", required: true }),
      F("lang_id", "kiosk.field.language", { type: "number", required: true }),
      F("text", "kiosk.field.text", { type: "textarea", required: true }),
    ],
    readOnlyReason: "kiosk.message.no_update_endpoint",
  },
  {
    slug: "lookup-types",
    title: "kiosk.view.lookup_types",
    description: "kiosk.view.lookup_types_desc",
    icon: "list",
    list: "/common/lookup-type/",
    create: "/common/lookup-type/",
    update: "/common/lookup-type/",
    remove: "/common/lookup-type/",
    idKey: "code",
    columns: [
      C("code", "kiosk.field.code"),
      C("name", "kiosk.field.name"),
      C("is_active", "kiosk.field.active"),
    ],
    fields: [
      F("code", "kiosk.field.code", { required: true }),
      F("name", "kiosk.field.name", { required: true }),
      F("is_active", "kiosk.field.active"),
    ],
  },
  {
    slug: "lookup-values",
    title: "kiosk.view.lookup_values",
    description: "kiosk.view.lookup_values_desc",
    icon: "list",
    list: "/common/lookup-value/",
    create: "/common/lookup-value/",
    update: "/common/lookup-value/",
    remove: "/common/lookup-value/",
    idKey: "code",
    columns: [
      C("code", "kiosk.field.code"),
      C("name", "kiosk.field.name"),
      C("type_code", "kiosk.field.type"),
      C("is_active", "kiosk.field.active"),
    ],
    fields: [
      F("code", "kiosk.field.code", { required: true }),
      F("name", "kiosk.field.name", { required: true }),
      F("type_code", "kiosk.field.type", { required: true }),
      F("is_active", "kiosk.field.active"),
    ],
  },
  {
    slug: "lookups",
    title: "kiosk.view.lookups",
    description: "kiosk.view.lookups_desc",
    icon: "list",
    list: "/common/lookups",
    idKey: "code",
    columns: [
      C("code", "kiosk.field.code"),
      C("name", "kiosk.field.name"),
      C("type_code", "kiosk.field.type"),
    ],
    readOnlyReason: "kiosk.message.combined_view",
  },
  {
    slug: "url-codes",
    title: "kiosk.view.url_codes",
    description: "kiosk.view.url_codes_desc",
    icon: "route",
    list: "/url_code",
    create: "/url_code",
    idKey: "code",
    columns: [C("code", "kiosk.field.code"), C("name", "kiosk.field.name")],
    fields: [
      F("code", "kiosk.field.code", { required: true }),
      F("name", "kiosk.field.name", { required: true }),
    ],
    readOnlyReason: "kiosk.message.no_update_endpoint",
  },

  // ── Directory and access ───────────────────────────────────────────────────
  {
    slug: "users",
    app: "kiosk-directory",
    title: "kiosk.view.users",
    description: "kiosk.view.users_desc",
    icon: "users",
    list: "/user/",
    remove: "/user/",
    columns: [
      C("id", "kiosk.field.id"),
      C("reg_no", "kiosk.field.reg_no"),
      C("last_name", "kiosk.field.last_name"),
      C("first_name", "kiosk.field.first_name"),
      C("card_serial_no", "kiosk.field.card"),
    ],
    readOnlyReason: "kiosk.message.core_owned",
  },
  {
    slug: "organizations",
    app: "kiosk-directory",
    title: "kiosk.view.organizations",
    description: "kiosk.view.organizations_desc",
    icon: "building",
    list: "/organization/",
    create: "/organization/",
    update: "/organization/",
    remove: "/organization/",
    columns: [
      C("id", "kiosk.field.id"),
      C("reg_no", "kiosk.field.reg_no"),
      C("name", "kiosk.field.name"),
      C("short_name", "kiosk.field.short_name"),
    ],
    fields: [
      F("reg_no", "kiosk.field.reg_no", { required: true }),
      F("name", "kiosk.field.name", { required: true }),
      F("short_name", "kiosk.field.short_name"),
    ],
  },
  {
    slug: "vehicles",
    app: "kiosk-directory",
    title: "kiosk.view.vehicles",
    description: "kiosk.view.vehicles_desc",
    icon: "truck",
    list: "/vehicle/",
    remove: "/vehicle/",
    columns: [
      C("id", "kiosk.field.id"),
      C("plate_no", "kiosk.field.plate"),
      C("mark_name", "kiosk.field.mark"),
      C("model_name", "kiosk.field.model"),
      C("owner_name", "kiosk.field.owner"),
    ],
    readOnlyReason: "kiosk.message.core_owned",
  },
  {
    slug: "roles",
    app: "kiosk-directory",
    title: "kiosk.view.roles",
    description: "kiosk.view.roles_desc",
    icon: "shield-check",
    list: "/role/",
    create: "/role/",
    update: "/role/",
    remove: "/role/",
    idKey: "code",
    columns: [
      C("code", "kiosk.field.code"),
      C("name", "kiosk.field.name"),
      C("system_code", "kiosk.field.system_code"),
    ],
    fields: [
      F("code", "kiosk.field.code", { required: true }),
      F("name", "kiosk.field.name", { required: true }),
      F("system_code", "kiosk.field.system_code"),
    ],
  },
  {
    slug: "resources",
    app: "kiosk-directory",
    title: "kiosk.view.resources",
    description: "kiosk.view.resources_desc",
    icon: "key-round",
    list: "/resource/",
    create: "/resource/",
    update: "/resource/",
    remove: "/resource/",
    idKey: "code",
    columns: [
      C("code", "kiosk.field.code"),
      C("name", "kiosk.field.name"),
      C("system_code", "kiosk.field.system_code"),
    ],
    fields: [
      F("code", "kiosk.field.code", { required: true }),
      F("name", "kiosk.field.name", { required: true }),
      F("system_code", "kiosk.field.system_code"),
    ],
  },
  {
    slug: "role-matrix",
    app: "kiosk-directory",
    title: "kiosk.view.role_matrix",
    description: "kiosk.view.role_matrix_desc",
    icon: "shield-check",
    list: "/role-matrix/",
    create: "/role-matrix/",
    remove: "/role-matrix/",
    columns: [
      C("role_code", "kiosk.field.role"),
      C("resource_code", "kiosk.field.resource"),
      C("permission", "kiosk.field.permission"),
    ],
    fields: [
      F("role_code", "kiosk.field.role", { required: true }),
      F("resource_code", "kiosk.field.resource", { required: true }),
      F("permission", "kiosk.field.permission"),
    ],
    readOnlyReason: "kiosk.message.no_update_endpoint",
  },
  {
    slug: "services",
    app: "kiosk-directory",
    title: "kiosk.view.services",
    description: "kiosk.view.services_desc",
    icon: "server-cog",
    list: "/system-service",
    create: "/system-service",
    update: "/system-service",
    remove: "/system-service",
    columns: [
      C("id", "kiosk.field.id"),
      C("name", "kiosk.field.name"),
      C("resource_code", "kiosk.field.resource"),
      C("method", "kiosk.field.method"),
      C("path", "kiosk.field.path"),
    ],
    fields: [
      F("name", "kiosk.field.name", { required: true }),
      F("resource_code", "kiosk.field.resource"),
      F("method", "kiosk.field.method"),
      F("path", "kiosk.field.path"),
      F("description", "kiosk.field.description", { type: "textarea" }),
    ],
  },
];

export const KIOSK_BY_SLUG: Record<string, KioskResource> = Object.fromEntries(
  KIOSK_RESOURCES.map((r) => [r.slug, r]),
);
